insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (1, '424', 'Kremasti puding', 'Predjelo', 156.58, 152.05, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (2, '414', 'Hot dog', 'Glavno jelo', 14.5, 236.33, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (3, '18', 'Pita s mesom', 'Desert', 136.13, 826.03, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (4, '368', 'Grilled cheese sandwich', 'Desert', 130.71, 447.38, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (5, '405', 'Tempura', 'Desert', 150.01, 982.97, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (6, '215', 'Crni rižoto', 'Desert', 217.75, 184.34, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (7, '472', 'Lasagne', 'Glavno jelo', 61.56, 132.84, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (8, '311', 'Pita od jabuka', 'Predjelo', 185.67, 19.32, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (9, '404', 'Grilled cheese sandwich', 'Glavno jelo', 150.34, 17.25, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (10, '386', 'Gulaš', 'Glavno jelo', 135.42, 97.04, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (11, '289', 'Tiramisu s jagodama', 'Predjelo', 158.91, 208.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (12, '439', 'Pomfrit', 'Predjelo', 217.46, 827.43, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (13, '400', 'Tempura', 'Desert', 55.28, 973.64, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (14, '138', 'Quesadilla', 'Desert', 170.36, 784.66, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (15, '485', 'Quesadilla', 'Predjelo', 105.05, 543.81, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (16, '269', 'Pizza Pepperoni', 'Glavno jelo', 161.62, 416.29, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (17, '373', 'Sladoled jagoda', 'Glavno jelo', 188.14, 557.28, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (18, '319', 'Torta s lješnjacima', 'Desert', 19.07, 148.54, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (19, '102', 'Kremasti puding', 'Glavno jelo', 115.0, 380.79, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (20, '167', 'Pita od špinata', 'Glavno jelo', 153.45, 786.58, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (21, '299', 'Pita od mesa', 'Desert', 170.68, 441.51, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (22, '140', 'Parfe', 'Desert', 25.56, 248.34, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (23, '275', 'Pizza Funghi', 'Predjelo', 195.73, 945.86, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (24, '3', 'Kremasti puding', 'Predjelo', 33.3, 245.05, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (25, '451', 'Pizza Capricciosa', 'Desert', 51.61, 831.77, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (26, '339', 'Cevapi', 'Desert', 135.6, 649.29, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (27, '483', 'Čizburger', 'Predjelo', 124.27, 860.91, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (28, '316', 'Pancake', 'Predjelo', 186.68, 410.41, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (29, '491', 'Frikadelle', 'Predjelo', 200.97, 56.95, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (30, '64', 'Torta s lješnjacima', 'Predjelo', 145.0, 694.47, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (31, '94', 'Pizza Funghi', 'Glavno jelo', 235.28, 130.57, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (32, '134', 'Kolač od mrkve', 'Desert', 58.12, 482.12, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (33, '69', 'Pita sa sirom', 'Glavno jelo', 118.34, 127.93, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (34, '190', 'Gyros', 'Predjelo', 14.18, 675.61, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (35, '351', 'Kremasti puding', 'Desert', 174.12, 350.75, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (36, '308', 'Cheeseburger', 'Desert', 85.11, 286.27, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (37, '178', 'Kebab', 'Desert', 59.77, 969.01, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (38, '240', 'Rižoto sa gljivama', 'Desert', 114.28, 823.13, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (39, '67', 'Cevapi', 'Glavno jelo', 26.88, 817.98, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (40, '71', 'Sarmica', 'Desert', 216.85, 787.23, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (41, '293', 'Paella', 'Desert', 248.97, 772.51, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (42, '10', 'Panna cotta', 'Glavno jelo', 85.78, 847.7, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (43, '442', 'Tiramisu s jagodama', 'Desert', 39.74, 163.26, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (44, '51', 'Sladoled čokolada', 'Desert', 69.89, 142.53, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (45, '389', 'Churros', 'Predjelo', 59.69, 71.74, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (46, '298', 'Riba na žaru', 'Desert', 146.35, 778.18, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (47, '176', 'Gulaš', 'Glavno jelo', 68.24, 838.99, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (48, '208', 'Falafel', 'Predjelo', 39.72, 592.69, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (49, '290', 'Pizza Vegetarijanska', 'Desert', 106.07, 274.07, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (50, '1', 'Kolač od mrkve', 'Glavno jelo', 218.58, 626.1, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (51, '44', 'Tiramisu s jagodama', 'Predjelo', 53.11, 9.84, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (52, '403', 'Parfe', 'Predjelo', 25.52, 748.27, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (53, '163', 'Filet mignon', 'Desert', 191.31, 779.65, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (54, '205', 'Cevapi', 'Desert', 18.29, 45.86, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (55, '272', 'Peking patka', 'Glavno jelo', 187.69, 857.02, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (56, '77', 'Stek', 'Glavno jelo', 110.93, 565.97, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (57, '100', 'Sladoled jagoda', 'Glavno jelo', 68.56, 499.92, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (58, '226', 'Pizza Diavola', 'Predjelo', 106.06, 795.51, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (59, '135', 'Torta s lješnjacima', 'Glavno jelo', 216.74, 507.58, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (60, '220', 'Paella', 'Predjelo', 49.49, 413.58, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (61, '101', 'Sushi', 'Glavno jelo', 39.72, 69.33, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (62, '469', 'Enchilada', 'Glavno jelo', 46.22, 912.16, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (63, '359', 'Sarmica', 'Glavno jelo', 85.08, 180.23, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (64, '371', 'Nachos', 'Predjelo', 70.93, 926.97, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (65, '258', 'Pita s mesom', 'Desert', 122.79, 210.24, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (66, '116', 'Cheesecake s malinama', 'Glavno jelo', 53.61, 529.05, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (67, '144', 'Pizza Pepperoni', 'Desert', 245.57, 388.63, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (68, '177', 'Pizza Capricciosa', 'Desert', 165.81, 506.61, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (69, '242', 'Quesadilla', 'Glavno jelo', 26.13, 406.17, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (70, '357', 'Pizza Vegetarijanska', 'Glavno jelo', 159.24, 139.45, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (71, '479', 'Gyros', 'Glavno jelo', 32.33, 129.77, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (72, '153', 'Punjena paprika', 'Glavno jelo', 56.77, 864.23, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (73, '286', 'Pasta Carbonara', 'Desert', 211.78, 937.76, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (74, '392', 'Torta od jagode', 'Glavno jelo', 157.5, 461.32, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (75, '150', 'Crni rižoto', 'Predjelo', 40.03, 297.17, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (76, '387', 'Cheesecake', 'Glavno jelo', 3.03, 413.73, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (77, '358', 'Churros', 'Glavno jelo', 191.62, 492.32, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (78, '103', 'Meksička burrito', 'Glavno jelo', 11.4, 917.24, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (79, '279', 'Filet mignon', 'Desert', 123.99, 656.4, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (80, '398', 'Riba na žaru', 'Predjelo', 201.32, 584.18, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (81, '184', 'Pizza Funghi', 'Glavno jelo', 233.27, 403.55, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (82, '105', 'Crni rižoto', 'Predjelo', 72.34, 663.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (83, '297', 'Paella', 'Glavno jelo', 105.87, 432.31, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (84, '202', 'Gulaš', 'Desert', 206.05, 443.34, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (85, '214', 'Nachos', 'Predjelo', 187.0, 7.05, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (86, '83', 'Brownie', 'Desert', 180.23, 21.23, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (87, '399', 'Sladoled vanilija', 'Glavno jelo', 197.16, 221.51, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (88, '196', 'Kebab', 'Glavno jelo', 215.14, 700.52, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (89, '92', 'Tiramisu', 'Glavno jelo', 113.14, 437.06, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (90, '498', 'Sarmica', 'Glavno jelo', 104.05, 982.91, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (91, '236', 'Taco', 'Desert', 53.09, 692.37, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (92, '32', 'Paella', 'Glavno jelo', 54.06, 487.51, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (93, '330', 'Pita sa povrćem', 'Predjelo', 218.56, 376.07, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (94, '302', 'Churros', 'Desert', 64.65, 842.91, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (95, '409', 'Brownie', 'Predjelo', 85.73, 336.52, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (96, '378', 'Caprese salata', 'Desert', 7.98, 23.69, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (97, '464', 'Hamburger', 'Glavno jelo', 151.92, 279.36, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (98, '166', 'Sladoled vanilija', 'Glavno jelo', 65.72, 941.89, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (99, '96', 'Pizza Pepperoni', 'Glavno jelo', 39.21, 716.15, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (100, '410', 'Čizburger', 'Glavno jelo', 52.81, 887.25, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (101, '417', 'Špageti Bolognese', 'Glavno jelo', 42.37, 593.98, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (102, '132', 'Sopa de tortilla', 'Predjelo', 4.86, 171.98, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (103, '39', 'Pizza Margherita', 'Glavno jelo', 201.66, 267.88, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (104, '276', 'Kebab', 'Glavno jelo', 112.29, 204.59, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (105, '33', 'Cheesecake s malinama', 'Predjelo', 40.8, 37.06, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (106, '193', 'Peking patka', 'Predjelo', 235.55, 976.9, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (107, '88', 'Sarma', 'Glavno jelo', 87.38, 377.53, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (108, '460', 'Kremasti puding', 'Predjelo', 168.68, 447.24, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (109, '310', 'Tiramisu', 'Glavno jelo', 15.29, 885.95, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (110, '437', 'Tempura', 'Predjelo', 150.83, 499.98, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (111, '35', 'Filet mignon', 'Glavno jelo', 34.59, 161.31, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (112, '355', 'Muffin od borovnice', 'Glavno jelo', 223.4, 33.38, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (113, '463', 'Pizza Vegetarijanska', 'Glavno jelo', 137.71, 372.57, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (114, '441', 'Pizza Margherita', 'Predjelo', 157.77, 315.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (115, '98', 'Pita od jabuka', 'Glavno jelo', 229.95, 544.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (116, '79', 'Enchilada', 'Predjelo', 120.91, 750.06, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (117, '335', 'Pita sa sirom', 'Glavno jelo', 195.65, 103.72, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (118, '365', 'Pizza Margherita', 'Desert', 152.71, 797.14, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (119, '11', 'Churros', 'Desert', 86.1, 838.12, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (120, '17', 'Pita od jabuka', 'Desert', 66.1, 116.66, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (121, '108', 'Puding od čokolade', 'Predjelo', 129.44, 593.37, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (122, '26', 'Meksička burrito', 'Desert', 217.35, 860.75, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (123, '292', 'Kolač od limuna', 'Predjelo', 191.62, 24.97, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (124, '273', 'Veganski burger', 'Desert', 96.76, 808.11, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (125, '256', 'Muffin od borovnice', 'Desert', 47.2, 299.44, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (126, '223', 'Puding od čokolade', 'Predjelo', 126.65, 297.5, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (127, '200', 'Sarma', 'Predjelo', 218.5, 68.71, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (128, '139', 'Hummus', 'Desert', 238.32, 73.85, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (129, '158', 'Tiramisu s jagodama', 'Glavno jelo', 107.62, 807.87, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (130, '24', 'Stek', 'Glavno jelo', 64.07, 202.15, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (131, '363', 'Grčki jogurt', 'Desert', 94.59, 432.87, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (132, '187', 'Pizza Vegetarijanska', 'Predjelo', 232.02, 740.93, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (133, '209', 'Sarmica', 'Glavno jelo', 138.12, 298.85, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (134, '68', 'Torta s lješnjacima', 'Desert', 19.39, 924.68, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (135, '274', 'Pizza Capricciosa', 'Desert', 154.71, 514.44, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (136, '280', 'Waffle', 'Desert', 153.22, 656.21, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (137, '249', 'Churros', 'Predjelo', 176.52, 127.03, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (138, '323', 'Brownie', 'Desert', 192.45, 918.72, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (139, '204', 'Pljeskavica', 'Glavno jelo', 249.29, 242.65, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (140, '194', 'Falafel', 'Glavno jelo', 83.24, 740.49, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (141, '122', 'Gyros', 'Desert', 35.94, 740.15, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (142, '490', 'Grilled cheese sandwich', 'Desert', 29.82, 76.23, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (143, '43', 'Kremasti puding', 'Predjelo', 19.92, 493.5, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (144, '47', 'Sashimi', 'Glavno jelo', 48.03, 847.66, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (145, '162', 'Puding od čokolade', 'Desert', 182.66, 284.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (146, '75', 'Cheesecake', 'Desert', 140.8, 348.69, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (147, '383', 'Čokoladni mousse', 'Glavno jelo', 90.86, 217.5, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (148, '219', 'Crni rižoto', 'Predjelo', 159.85, 853.03, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (149, '175', 'Piletina u umaku od meda i senfa', 'Glavno jelo', 199.12, 819.69, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (150, '74', 'Puding od čokolade', 'Predjelo', 59.14, 978.38, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (151, '80', 'Čokoladni mousse', 'Desert', 29.23, 301.05, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (152, '206', 'Grilled cheese sandwich', 'Predjelo', 15.95, 765.73, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (153, '259', 'Pomfrit', 'Desert', 234.45, 343.39, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (154, '179', 'Cevapi', 'Glavno jelo', 68.58, 315.77, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (155, '324', 'Tequila shrimp', 'Glavno jelo', 88.59, 501.91, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (156, '239', 'Sopa de tortilla', 'Desert', 1.62, 605.53, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (157, '237', 'Grilani lignji', 'Desert', 91.78, 577.56, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (158, '192', 'Veganski burger', 'Desert', 168.71, 111.67, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (159, '364', 'Churros', 'Desert', 236.13, 96.22, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (160, '199', 'Pita od špinata', 'Glavno jelo', 217.49, 459.56, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (161, '384', 'Panna cotta', 'Desert', 38.53, 957.17, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (162, '266', 'Pizza Quattro Stagioni', 'Desert', 119.5, 625.56, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (163, '30', 'Lasagne', 'Desert', 53.19, 200.25, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (164, '493', 'Grilani lignji', 'Desert', 179.57, 962.37, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (165, '78', 'Parfe', 'Glavno jelo', 225.94, 474.86, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (166, '217', 'Cheesecake s malinama', 'Predjelo', 147.49, 779.03, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (167, '350', 'Guacamole', 'Desert', 203.25, 527.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (168, '245', 'Cevapi', 'Predjelo', 207.03, 672.33, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (169, '230', 'Pita sa sirom', 'Desert', 106.1, 547.65, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (170, '497', 'Pizza Quattro Stagioni', 'Desert', 231.04, 185.07, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (171, '126', 'Brownie', 'Predjelo', 133.77, 193.86, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (172, '457', 'Pita od jabuka', 'Desert', 158.72, 692.9, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (173, '238', 'Crni rižoto', 'Predjelo', 208.88, 336.39, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (174, '393', 'Caprese salata', 'Predjelo', 27.85, 936.92, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (175, '188', 'Tequila shrimp', 'Glavno jelo', 88.75, 554.75, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (176, '89', 'Čokoladni mousse', 'Glavno jelo', 249.11, 297.16, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (177, '186', 'Pasta Carbonara', 'Desert', 17.74, 589.06, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (178, '455', 'Grilled cheese sandwich', 'Glavno jelo', 186.25, 946.5, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (179, '467', 'Puding od čokolade', 'Predjelo', 242.14, 997.64, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (180, '123', 'Veganski burger', 'Glavno jelo', 61.2, 438.45, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (181, '128', 'Pita sa povrćem', 'Desert', 6.95, 456.68, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (182, '137', 'Špageti Bolognese', 'Predjelo', 164.61, 148.51, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (183, '309', 'Punjena paprika', 'Desert', 16.05, 512.24, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (184, '325', 'Kolač od limuna', 'Desert', 166.79, 584.37, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (185, '461', 'Tiramisu s jagodama', 'Desert', 170.79, 495.57, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (186, '156', 'Pizza Margherita', 'Predjelo', 44.4, 803.13, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (187, '277', 'Grilled cheese sandwich', 'Predjelo', 144.21, 563.89, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (188, '7', 'Pizza Funghi', 'Glavno jelo', 104.37, 265.25, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (189, '429', 'Torta od jagode', 'Glavno jelo', 16.66, 584.96, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (190, '168', 'Tempura', 'Glavno jelo', 211.36, 896.92, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (191, '303', 'Okonomiyaki', 'Predjelo', 201.88, 964.48, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (192, '438', 'Pita sa sirom', 'Glavno jelo', 14.33, 766.53, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (193, '379', 'Sladoled čokolada', 'Glavno jelo', 224.32, 954.47, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (194, '484', 'Stek', 'Predjelo', 1.95, 650.28, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (195, '136', 'Cezar salata', 'Glavno jelo', 149.47, 683.61, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (196, '172', 'Pita od špinata', 'Glavno jelo', 67.47, 657.22, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (197, '152', 'Taco', 'Predjelo', 193.34, 447.3, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (198, '301', 'Quesadilla', 'Predjelo', 167.15, 694.28, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (199, '155', 'Kolač od limuna', 'Glavno jelo', 8.58, 711.72, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (200, '388', 'Kolač od mrkve', 'Desert', 159.36, 486.16, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (201, '337', 'Meksička burrito', 'Desert', 95.45, 25.24, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (202, '114', 'Paella', 'Desert', 209.13, 801.54, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (203, '395', 'Panna cotta', 'Desert', 62.72, 906.34, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (204, '369', 'Hamburger', 'Glavno jelo', 190.82, 662.39, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (205, '118', 'Grilled cheese sandwich', 'Predjelo', 122.03, 517.73, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (206, '492', 'Pizza Vegetarijanska', 'Glavno jelo', 249.68, 689.34, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (207, '344', 'Pizza Diavola', 'Glavno jelo', 63.42, 472.36, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (208, '203', 'Pizza Diavola', 'Predjelo', 56.66, 857.23, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (209, '471', 'Caprese salata', 'Glavno jelo', 216.18, 324.37, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (210, '58', 'Nachos', 'Glavno jelo', 161.12, 6.92, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (211, '406', 'Pita s mesom', 'Glavno jelo', 128.6, 142.62, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (212, '362', 'Taco', 'Desert', 148.03, 966.6, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (213, '181', 'Tiramisu', 'Predjelo', 141.93, 297.04, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (214, '418', 'Quesadilla', 'Predjelo', 197.93, 337.73, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (215, '221', 'Čokoladni mousse', 'Predjelo', 220.74, 631.04, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (216, '180', 'Muffin od borovnice', 'Desert', 62.94, 605.0, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (217, '445', 'Sladoled vanilija', 'Predjelo', 244.62, 551.04, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (218, '222', 'Brownie', 'Predjelo', 169.13, 638.3, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (219, '436', 'Hummus', 'Desert', 22.3, 858.37, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (220, '381', 'Punjena paprika', 'Desert', 15.29, 621.39, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (221, '300', 'Pizza Quattro Stagioni', 'Desert', 224.54, 989.66, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (222, '212', 'Tiramisu', 'Glavno jelo', 55.0, 181.36, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (223, '70', 'Frutti di mare', 'Desert', 195.75, 152.49, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (224, '174', 'Piletina u umaku od meda i senfa', 'Glavno jelo', 1.44, 129.74, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (225, '390', 'Patlidzan', 'Predjelo', 97.96, 986.72, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (226, '224', 'Grčki jogurt', 'Predjelo', 61.52, 59.29, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (227, '22', 'Lasagne', 'Desert', 249.71, 45.55, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (228, '264', 'Sopa de tortilla', 'Glavno jelo', 174.94, 344.18, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (229, '496', 'Guacamole', 'Desert', 20.38, 818.33, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (230, '73', 'Hummus', 'Glavno jelo', 76.45, 379.07, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (231, '16', 'Piletina u umaku od meda i senfa', 'Desert', 246.34, 800.96, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (232, '8', 'Kremasti puding', 'Desert', 115.05, 457.68, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (233, '361', 'Sopa de tortilla', 'Predjelo', 227.15, 774.6, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (234, '49', 'Cezar salata', 'Glavno jelo', 239.4, 488.16, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (235, '31', 'Parfe', 'Glavno jelo', 20.2, 530.68, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (236, '211', 'Grilled cheese sandwich', 'Desert', 7.77, 979.27, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (237, '322', 'Pita sa povrćem', 'Desert', 59.28, 876.11, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (238, '314', 'Pizza Pepperoni', 'Predjelo', 182.62, 855.56, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (239, '435', 'Meksička burrito', 'Desert', 118.01, 770.87, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (240, '197', 'Pomfrit', 'Desert', 46.25, 11.42, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (241, '46', 'Veganski burger', 'Desert', 217.36, 453.06, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (242, '401', 'Pizza Diavola', 'Predjelo', 76.68, 648.86, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (243, '120', 'Grilani lignji', 'Glavno jelo', 170.19, 364.15, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (244, '474', 'Okonomiyaki', 'Desert', 93.73, 60.63, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (245, '157', 'Falafel', 'Glavno jelo', 97.47, 877.92, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (246, '434', 'Lignje', 'Desert', 191.54, 146.34, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (247, '462', 'Pita od mesa', 'Predjelo', 183.84, 706.31, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (248, '366', 'Hamburger', 'Predjelo', 12.96, 238.82, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (249, '50', 'Pita sa povrćem', 'Predjelo', 60.88, 602.88, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (250, '207', 'Gyros', 'Desert', 248.07, 408.0, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (251, '408', 'Pomfrit', 'Desert', 189.56, 450.02, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (252, '478', 'Čizburger', 'Glavno jelo', 159.26, 860.55, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (253, '376', 'Rižoto sa gljivama', 'Glavno jelo', 71.17, 2.68, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (254, '183', 'Rižoto sa gljivama', 'Desert', 72.4, 250.54, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (255, '416', 'Sarmica', 'Predjelo', 32.94, 337.27, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (256, '250', 'Pizza Vegetarijanska', 'Predjelo', 78.52, 793.78, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (257, '111', 'Pizza Margherita', 'Glavno jelo', 27.32, 413.52, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (258, '283', 'Rižoto sa gljivama', 'Glavno jelo', 109.41, 666.91, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (259, '216', 'Sladoled vanilija', 'Glavno jelo', 87.35, 856.47, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (260, '500', 'Donut', 'Glavno jelo', 187.45, 770.18, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (261, '420', 'Puding od čokolade', 'Desert', 227.46, 516.5, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (262, '341', 'Brownie', 'Glavno jelo', 162.77, 123.14, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (263, '454', 'Pljeskavica', 'Predjelo', 239.31, 85.72, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (264, '338', 'Cheesecake', 'Desert', 108.19, 512.48, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (265, '119', 'Pita od jabuka', 'Predjelo', 192.35, 197.1, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (266, '243', 'Grčki jogurt', 'Predjelo', 168.34, 406.86, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (267, '427', 'Parfe', 'Desert', 125.54, 452.75, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (268, '486', 'Meksička burrito', 'Desert', 229.55, 427.05, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (269, '320', 'Paella', 'Predjelo', 117.8, 474.82, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (270, '244', 'Pita od špinata', 'Glavno jelo', 229.87, 854.34, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (271, '315', 'Gulaš', 'Glavno jelo', 155.26, 64.22, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (272, '466', 'Okonomiyaki', 'Desert', 143.86, 617.89, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (273, '332', 'Pizza Diavola', 'Predjelo', 4.66, 781.13, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (274, '468', 'Waffle', 'Desert', 8.18, 681.49, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (275, '305', 'Sladoled jagoda', 'Predjelo', 205.45, 168.4, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (276, '189', 'Kolač od limuna', 'Glavno jelo', 196.82, 782.53, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (277, '52', 'Cezar salata', 'Desert', 138.77, 180.04, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (278, '421', 'Pljeskavica', 'Desert', 23.86, 468.68, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (279, '147', 'Gulaš', 'Desert', 114.8, 507.35, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (280, '431', 'Gulaš', 'Desert', 22.38, 654.14, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (281, '66', 'Pizza Vegetarijanska', 'Predjelo', 62.61, 820.95, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (282, '391', 'Pizza Capricciosa', 'Predjelo', 145.0, 103.53, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (283, '91', 'Frutti di mare', 'Desert', 105.08, 847.44, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (284, '231', 'Sashimi', 'Glavno jelo', 240.1, 440.04, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (285, '161', 'Kebab', 'Predjelo', 188.22, 683.31, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (286, '36', 'Lasagne', 'Desert', 225.27, 321.26, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (287, '270', 'Grilled cheese sandwich', 'Glavno jelo', 243.01, 758.12, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (288, '15', 'Pizza Quattro Stagioni', 'Predjelo', 82.02, 3.84, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (289, '446', 'Pizza Capricciosa', 'Predjelo', 102.71, 484.23, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (290, '296', 'Muffin od borovnice', 'Predjelo', 224.9, 50.79, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (291, '288', 'Kolač od mrkve', 'Glavno jelo', 112.67, 14.02, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (292, '306', 'Pizza Diavola', 'Predjelo', 47.19, 375.57, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (293, '34', 'Pizza Vegetarijanska', 'Desert', 93.52, 888.09, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (294, '312', 'Torta od jagode', 'Desert', 136.56, 564.2, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (295, '254', 'Hot dog', 'Predjelo', 15.8, 734.92, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (296, '261', 'Pizza Funghi', 'Glavno jelo', 108.01, 83.04, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (297, '84', 'Grilani lignji', 'Predjelo', 198.79, 766.32, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (298, '480', 'Tiramisu s jagodama', 'Predjelo', 218.62, 965.11, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (299, '321', 'Piletina u umaku od meda i senfa', 'Glavno jelo', 116.39, 821.8, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (300, '411', 'Pita s mesom', 'Predjelo', 175.19, 921.56, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (301, '131', 'Pita od jabuka', 'Glavno jelo', 127.47, 800.35, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (302, '260', 'Pizza Margherita', 'Predjelo', 20.06, 797.47, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (303, '164', 'Kolač od limuna', 'Desert', 134.19, 495.44, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (304, '41', 'Tiramisu s jagodama', 'Predjelo', 177.82, 314.22, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (305, '428', 'Stek', 'Predjelo', 204.84, 154.99, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (306, '470', 'Pita od špinata', 'Desert', 221.25, 800.51, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (307, '42', 'Okonomiyaki', 'Predjelo', 117.0, 402.88, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (308, '60', 'Grilani lignji', 'Glavno jelo', 76.76, 196.04, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (309, '159', 'Pomfrit', 'Glavno jelo', 76.24, 492.35, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (310, '5', 'Tiramisu', 'Glavno jelo', 111.34, 88.79, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (311, '232', 'Sarma', 'Glavno jelo', 165.81, 364.64, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (312, '370', 'Guacamole', 'Glavno jelo', 174.46, 701.22, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (313, '97', 'Pizza Pepperoni', 'Predjelo', 40.74, 676.88, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (314, '465', 'Gyros', 'Glavno jelo', 197.96, 687.63, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (315, '139', 'Muffin od borovnice', 'Glavno jelo', 71.11, 69.51, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (316, '224', 'Cheesecake s malinama', 'Glavno jelo', 12.78, 129.63, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (317, '121', 'Cheeseburger', 'Desert', 170.1, 416.21, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (318, '454', 'Tempura', 'Predjelo', 11.9, 840.76, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (319, '147', 'Pizza Quattro Stagioni', 'Predjelo', 12.37, 924.93, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (320, '117', 'Paella', 'Desert', 83.86, 635.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (321, '99', 'Filet mignon', 'Desert', 105.53, 376.41, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (322, '215', 'Pomfrit', 'Desert', 32.76, 14.61, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (323, '296', 'Tiramisu s jagodama', 'Glavno jelo', 240.24, 148.54, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (324, '474', 'Waffle', 'Predjelo', 200.84, 203.59, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (325, '158', 'Gulaš', 'Desert', 55.54, 245.16, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (326, '350', 'Pita sa povrćem', 'Desert', 4.07, 779.33, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (327, '204', 'Parfe', 'Predjelo', 41.82, 508.8, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (328, '104', 'Kineski rezanci', 'Desert', 215.26, 866.97, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (329, '20', 'Hamburger', 'Glavno jelo', 12.98, 992.94, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (330, '166', 'Guacamole', 'Glavno jelo', 16.75, 752.65, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (331, '436', 'Pomfrit', 'Predjelo', 99.36, 91.06, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (332, '192', 'Tiramisu s jagodama', 'Desert', 48.09, 689.14, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (333, '312', 'Waffle', 'Desert', 242.44, 243.0, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (334, '451', 'Lasagne', 'Predjelo', 180.12, 942.68, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (335, '169', 'Grilani lignji', 'Desert', 86.04, 922.05, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (336, '463', 'Falafel', 'Desert', 9.11, 213.47, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (337, '332', 'Gyros', 'Predjelo', 19.12, 168.27, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (338, '460', 'Cheesecake s malinama', 'Predjelo', 124.94, 977.82, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (339, '310', 'Donut', 'Glavno jelo', 69.72, 725.16, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (340, '94', 'Cevapi', 'Glavno jelo', 224.27, 396.33, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (341, '6', 'Crni rižoto', 'Desert', 117.15, 541.1, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (342, '284', 'Sushi', 'Desert', 123.19, 357.1, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (343, '414', 'Pljeskavica', 'Desert', 47.63, 184.84, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (344, '283', 'Peking patka', 'Desert', 56.37, 856.87, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (345, '230', 'Muffin od borovnice', 'Glavno jelo', 24.44, 129.4, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (346, '189', 'Torta s lješnjacima', 'Desert', 166.35, 420.37, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (347, '278', 'Tequila shrimp', 'Desert', 39.25, 305.86, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (348, '387', 'Okonomiyaki', 'Glavno jelo', 202.3, 133.17, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (349, '129', 'Pizza Vegetarijanska', 'Predjelo', 222.57, 990.06, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (350, '172', 'Kolač od limuna', 'Glavno jelo', 55.86, 595.22, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (351, '390', 'Pancake', 'Glavno jelo', 157.41, 30.6, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (352, '257', 'Piletina u umaku od meda i senfa', 'Glavno jelo', 240.36, 345.85, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (353, '98', 'Gulaš', 'Desert', 187.54, 857.04, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (354, '321', 'Paella', 'Desert', 72.26, 596.4, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (355, '324', 'Veganski burger', 'Desert', 101.93, 794.18, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (356, '232', 'Čokoladni mousse', 'Desert', 86.49, 41.96, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (357, '15', 'Brownie', 'Predjelo', 119.55, 570.13, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (358, '467', 'Hummus', 'Desert', 96.79, 479.35, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (359, '328', 'Hamburger', 'Desert', 187.02, 194.03, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (360, '416', 'Torta od jagode', 'Glavno jelo', 3.17, 464.8, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (361, '456', 'Panna cotta', 'Glavno jelo', 240.17, 631.61, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (362, '41', 'Pita od špinata', 'Desert', 232.27, 576.24, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (363, '381', 'Okonomiyaki', 'Predjelo', 51.02, 433.48, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (364, '302', 'Guacamole', 'Desert', 113.26, 631.05, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (365, '248', 'Cezar salata', 'Predjelo', 227.74, 32.83, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (366, '161', 'Pomfrit', 'Glavno jelo', 155.4, 957.28, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (367, '10', 'Muffin od borovnice', 'Desert', 125.89, 686.8, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (368, '361', 'Pizza Margherita', 'Predjelo', 178.79, 900.73, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (369, '490', 'Tiramisu s jagodama', 'Predjelo', 71.39, 858.53, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (370, '488', 'Riba na žaru', 'Glavno jelo', 150.78, 53.41, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (371, '326', 'Pita sa povrćem', 'Glavno jelo', 107.91, 917.99, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (372, '64', 'Tiramisu s jagodama', 'Desert', 216.13, 807.23, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (373, '268', 'Kolač od mrkve', 'Desert', 232.61, 737.91, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (374, '153', 'Hamburger', 'Glavno jelo', 35.06, 186.04, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (375, '221', 'Peking patka', 'Glavno jelo', 69.21, 813.6, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (376, '112', 'Filet mignon', 'Desert', 42.76, 348.64, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (377, '44', 'Pita od jabuka', 'Predjelo', 119.02, 651.44, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (378, '53', 'Pasta Carbonara', 'Glavno jelo', 189.59, 52.02, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (379, '188', 'Cheeseburger', 'Desert', 171.98, 938.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (380, '403', 'Frutti di mare', 'Glavno jelo', 67.27, 636.86, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (381, '124', 'Pizza Funghi', 'Predjelo', 10.61, 12.3, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (382, '14', 'Špageti Bolognese', 'Predjelo', 150.26, 246.14, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (383, '466', 'Guacamole', 'Predjelo', 12.36, 248.06, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (384, '72', 'Riba na žaru', 'Glavno jelo', 11.63, 216.6, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (385, '469', 'Gyros', 'Predjelo', 186.28, 714.92, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (386, '439', 'Pizza Margherita', 'Glavno jelo', 24.22, 565.35, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (387, '365', 'Pileći burger', 'Predjelo', 176.98, 206.84, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (388, '334', 'Enchilada', 'Desert', 245.76, 874.33, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (389, '447', 'Sladoled vanilija', 'Desert', 178.86, 232.36, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (390, '293', 'Brownie', 'Predjelo', 117.4, 349.1, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (391, '222', 'Pita sa sirom', 'Glavno jelo', 162.71, 436.34, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (392, '208', 'Parfe', 'Desert', 91.63, 554.39, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (393, '27', 'Torta s lješnjacima', 'Glavno jelo', 211.13, 634.78, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (394, '306', 'Tiramisu s jagodama', 'Desert', 245.31, 703.52, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (395, '497', 'Piletina u umaku od meda i senfa', 'Predjelo', 163.1, 623.79, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (396, '19', 'Kolač od limuna', 'Predjelo', 131.41, 489.65, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (397, '237', 'Kolač od mrkve', 'Glavno jelo', 78.18, 943.74, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (398, '462', 'Kolač od mrkve', 'Predjelo', 74.28, 504.04, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (399, '213', 'Pancake', 'Desert', 231.41, 340.75, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (400, '171', 'Falafel', 'Predjelo', 177.07, 977.55, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (401, '209', 'Gulaš', 'Glavno jelo', 10.12, 246.03, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (402, '329', 'Sarma', 'Predjelo', 153.39, 564.3, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (403, '234', 'Hummus', 'Predjelo', 112.23, 77.55, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (404, '271', 'Rižoto sa gljivama', 'Predjelo', 133.31, 872.29, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (405, '496', 'Grilled cheese sandwich', 'Predjelo', 170.16, 756.79, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (406, '345', 'Stek', 'Glavno jelo', 240.91, 988.51, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (407, '155', 'Pita s mesom', 'Glavno jelo', 184.11, 214.76, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (408, '142', 'Čizburger', 'Desert', 32.12, 261.85, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (409, '238', 'Puding od čokolade', 'Predjelo', 53.15, 922.32, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (410, '419', 'Pancake', 'Glavno jelo', 3.22, 611.04, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (411, '307', 'Meksička burrito', 'Desert', 41.87, 992.79, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (412, '314', 'Pizza Capricciosa', 'Desert', 235.46, 595.0, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (413, '487', 'Nachos', 'Predjelo', 64.76, 612.9, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (414, '5', 'Frutti di mare', 'Glavno jelo', 81.24, 332.65, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (415, '243', 'Quesadilla', 'Glavno jelo', 68.17, 696.81, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (416, '211', 'Tempura', 'Desert', 155.16, 188.89, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (417, '358', 'Pancake', 'Predjelo', 229.52, 106.56, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (418, '126', 'Pasta Carbonara', 'Glavno jelo', 134.11, 725.49, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (419, '258', 'Špageti Bolognese', 'Predjelo', 124.77, 506.69, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (420, '291', 'Quesadilla', 'Predjelo', 241.9, 372.79, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (421, '250', 'Gulaš', 'Predjelo', 140.54, 573.35, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (422, '475', 'Cheesecake', 'Predjelo', 84.91, 452.37, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (423, '240', 'Pizza Quattro Stagioni', 'Desert', 82.19, 689.07, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (424, '231', 'Čokoladni mousse', 'Predjelo', 56.21, 312.01, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (425, '323', 'Cevapi', 'Predjelo', 130.81, 361.42, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (426, '217', 'Rižoto sa gljivama', 'Glavno jelo', 49.95, 186.63, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (427, '285', 'Pizza Vegetarijanska', 'Desert', 53.97, 702.75, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (428, '369', 'Pita s mesom', 'Desert', 158.37, 579.79, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (429, '315', 'Peking patka', 'Predjelo', 73.4, 823.91, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (430, '330', 'Gulaš', 'Predjelo', 160.75, 915.65, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (431, '477', 'Parfe', 'Glavno jelo', 188.2, 883.44, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (432, '401', 'Enchilada', 'Predjelo', 196.38, 107.27, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (433, '485', 'Pita s mesom', 'Desert', 185.37, 519.33, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (434, '69', 'Sarmica', 'Predjelo', 89.83, 675.9, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (435, '428', 'Čizburger', 'Predjelo', 88.02, 2.07, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (436, '389', 'Caprese salata', 'Predjelo', 162.66, 762.45, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (437, '426', 'Frikadelle', 'Predjelo', 179.95, 293.84, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (438, '340', 'Kolač od mrkve', 'Predjelo', 170.54, 996.18, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (439, '1', 'Brownie', 'Predjelo', 231.91, 743.63, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (440, '269', 'Peking patka', 'Glavno jelo', 38.87, 849.87, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (441, '408', 'Pizza Vegetarijanska', 'Desert', 76.17, 155.15, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (442, '371', 'Falafel', 'Glavno jelo', 101.29, 387.69, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (443, '423', 'Pomfrit', 'Glavno jelo', 57.98, 727.59, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (444, '434', 'Crni rižoto', 'Glavno jelo', 40.33, 293.67, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (445, '103', 'Piletina u umaku od meda i senfa', 'Predjelo', 181.66, 829.55, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (446, '244', 'Kremasti puding', 'Desert', 204.81, 463.94, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (447, '212', 'Pita od jabuka', 'Predjelo', 205.19, 411.29, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (448, '160', 'Kineski rezanci', 'Predjelo', 11.12, 96.97, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (449, '190', 'Gulaš', 'Predjelo', 191.73, 351.3, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (450, '133', 'Pita sa sirom', 'Predjelo', 65.78, 965.48, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (451, '286', 'Hamburger', 'Desert', 12.97, 528.52, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (452, '351', 'Stek', 'Predjelo', 165.42, 340.8, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (453, '198', 'Churros', 'Predjelo', 152.6, 426.48, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (454, '281', 'Grilani lignji', 'Desert', 230.48, 697.24, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (455, '259', 'Tiramisu', 'Predjelo', 17.78, 29.38, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (456, '246', 'Punjena paprika', 'Predjelo', 191.46, 182.79, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (457, '201', 'Tempura', 'Predjelo', 239.09, 630.99, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (458, '263', 'Grilled cheese sandwich', 'Desert', 199.12, 667.18, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (459, '360', 'Veganski burger', 'Desert', 68.18, 928.53, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (460, '38', 'Pizza Vegetarijanska', 'Predjelo', 110.72, 173.59, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (461, '298', 'Pizza Capricciosa', 'Glavno jelo', 95.97, 883.14, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (462, '319', 'Parfe', 'Desert', 212.64, 302.56, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (463, '90', 'Sarmica', 'Glavno jelo', 96.44, 278.27, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (464, '86', 'Tiramisu', 'Glavno jelo', 25.38, 198.81, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (465, '156', 'Peking patka', 'Predjelo', 58.76, 204.64, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (466, '479', 'Nachos', 'Predjelo', 36.57, 97.99, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (467, '223', 'Peking patka', 'Desert', 19.55, 597.18, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (468, '52', 'Gyros', 'Desert', 191.37, 950.96, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (469, '473', 'Frutti di mare', 'Desert', 30.67, 791.64, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (470, '101', 'Okonomiyaki', 'Predjelo', 62.33, 166.28, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (471, '354', 'Peking patka', 'Glavno jelo', 71.35, 185.19, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (472, '135', 'Čokoladni mousse', 'Glavno jelo', 84.3, 563.65, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (473, '95', 'Guacamole', 'Desert', 181.91, 905.59, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (474, '295', 'Grčki jogurt', 'Glavno jelo', 35.39, 566.61, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (475, '318', 'Brownie', 'Predjelo', 23.2, 586.3, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (476, '425', 'Veganski burger', 'Predjelo', 214.66, 807.51, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (477, '178', 'Tempura', 'Glavno jelo', 92.2, 561.02, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (478, '45', 'Waffle', 'Predjelo', 3.88, 251.91, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (479, '370', 'Nachos', 'Predjelo', 82.44, 798.97, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (480, '471', 'Grčki jogurt', 'Predjelo', 4.28, 196.73, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (481, '184', 'Parfe', 'Glavno jelo', 51.16, 300.24, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (482, '25', 'Falafel', 'Desert', 146.99, 594.33, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (483, '491', 'Riba na žaru', 'Predjelo', 175.83, 927.53, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (484, '249', 'Caprese salata', 'Predjelo', 75.42, 605.23, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (485, '16', 'Cheesecake s malinama', 'Glavno jelo', 77.7, 795.83, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (486, '380', 'Frutti di mare', 'Predjelo', 106.61, 487.92, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (487, '287', 'Sopa de tortilla', 'Desert', 208.09, 253.31, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (488, '386', 'Cheeseburger', 'Desert', 211.8, 756.16, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (489, '13', 'Lasagne', 'Desert', 59.76, 967.16, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (490, '159', 'Guacamole', 'Glavno jelo', 126.99, 966.62, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (491, '261', 'Torta s lješnjacima', 'Predjelo', 109.0, 312.54, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (492, '229', 'Crni rižoto', 'Desert', 62.34, 887.77, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (493, '177', 'Parfe', 'Desert', 199.32, 998.25, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (494, '150', 'Waffle', 'Desert', 178.43, 761.91, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (495, '34', 'Hot dog', 'Glavno jelo', 115.44, 193.74, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (496, '206', 'Tiramisu', 'Predjelo', 180.16, 709.18, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (497, '444', 'Donut', 'Glavno jelo', 3.26, 838.79, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (498, '4', 'Sladoled jagoda', 'Desert', 226.62, 599.48, 'Dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (499, '300', 'Brownie', 'Desert', 214.82, 750.65, 'Ne dostupno');
insert into Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability) values (500, '87', 'Tempura', 'Desert', 17.64, 315.52, 'Ne dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (501, 518, 'chocolate cake', 'Desert', 8.50, 300, 'Dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (502, 519, 'apple pie', 'Desert', 7.00, 250, 'Dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (503, 518, 'tiramisu', 'Desert', 9.00, 400, 'Dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (504, 519, 'cheesecake', 'Desert', 7.50, 350, 'Ne dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (505, 518, 'fruit salad', 'Desert', 5.00, 200, 'Dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (506, 520, 'Chocolate Cake', 'Desert', 8.50, 300, 'Dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (507, 520, 'Apple Pie', 'Desert', 6.50, 250, 'Dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (508, 520, 'Strawberry Tart', 'Desert', 7.00, 280, 'Dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (509, 520, 'Lemon Meringue Pie', 'Desert', 6.00, 270, 'Dostupno');
insert into foods (foodid, restaurantid, name, category, price, calories, availability) values (510, 520, 'Cheesecake', 'Desert', 9.00, 350, 'Dostupno');
INSERT INTO Foods (FoodId, RestaurantId, Name, Category, Price, Calories, Availability)
VALUES 
(511, 521, 'Chocolate Cake', 'Desert', 7.50, 300, 'Dostupno'),
(512, 522, 'Tiramisu', 'Desert', 6.00, 250, 'Dostupno'),
(513, 523, 'Fruit Salad', 'Desert', 5.00, 150, 'Dostupno'),
(514, 524, 'Cheese Cake', 'Desert', 8.00, 400, 'Dostupno'),
(515, 525, 'Apple Pie', 'Desert', 5.50, 350, 'Dostupno');



