insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (1, 'Glover, Stracke and Haley', 'Jianli', 28, '8:17 AM', '8:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (2, 'Hickle, Kris and Ebert', 'Vallentuna', 47, '8:00 AM', '8:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (3, 'O''Conner, Bernhard and Tromp', 'El Matama', 96, '8:27 AM', '9:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (4, 'Bode Inc', 'Xiapu', 77, '8:43 AM', '8:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (5, 'Hoppe LLC', 'Lubaczów', 59, '8:52 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (6, 'Torphy LLC', 'Куклиш', 57, '8:58 AM', '8:35 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (7, 'Heaney, Murazik and Johnson', 'La Paz', 51, '9:54 AM', '8:10 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (8, 'Littel, Swift and Crona', 'Megulung', 38, '8:33 AM', '8:27 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (9, 'Moore-Christiansen', 'Kablukan', 39, '9:19 AM', '8:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (10, 'Schaefer, Sanford and Bayer', 'Gaoqiao', 28, '9:44 AM', '8:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (11, 'Purdy-Nikolaus', 'Jaworzyna Śląska', 42, '9:04 AM', '9:34 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (12, 'Hettinger-Moen', 'Dorp Antriol', 71, '9:09 AM', '9:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (13, 'Kunze LLC', 'Las Minas', 37, '9:23 AM', '8:44 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (14, 'Stoltenberg, Schulist and Oberbrunner', 'Ngrejo', 15, '9:42 AM', '9:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (15, 'Yundt Inc', 'Lučko', 19, '8:17 AM', '8:52 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (16, 'Tromp, Sanford and Larson', 'Zhyrovichy', 54, '8:06 AM', '9:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (17, 'Hilll, Shields and Robel', 'Arroteia', 32, '9:22 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (18, 'Bailey, Bruen and Schowalter', 'Bissau', 92, '9:03 AM', '9:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (19, 'Wintheiser-Tromp', 'Skogås', 63, '8:40 AM', '8:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (20, 'Auer LLC', 'Youxi', 51, '8:46 AM', '9:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (21, 'Klein, Robel and Turcotte', 'Bacacay', 91, '9:08 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (22, 'King-Schuster', 'Sbo’o', 31, '9:51 AM', '9:03 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (23, 'Armstrong LLC', 'Heshan', 99, '8:31 AM', '9:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (24, 'Gerhold-Runolfsdottir', 'Humaitá', 41, '8:04 AM', '8:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (25, 'Powlowski, Hermann and Romaguera', 'Belo', 64, '9:23 AM', '8:05 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (26, 'Fisher-Johnson', 'Hostavice', 42, '8:30 AM', '8:03 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (27, 'Veum-Brakus', 'Cihampelas', 84, '8:26 AM', '9:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (28, 'Dach, Herman and Walsh', 'Kwikila', 40, '9:51 AM', '9:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (29, 'Abbott and Sons', 'Chokwé', 5, '8:18 AM', '8:24 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (30, 'Corwin LLC', 'Khorol', 78, '8:11 AM', '9:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (31, 'Thiel Group', 'Camias', 85, '8:51 AM', '8:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (32, 'Turner, Mitchell and Gleason', 'Ungaran', 16, '9:03 AM', '8:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (33, 'Hickle, Wiza and Mraz', 'Nanxing', 99, '8:51 AM', '9:27 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (34, 'Aufderhar Group', 'Głuchów', 64, '8:37 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (35, 'Yundt-Fisher', 'Jijiazhuang', 90, '9:04 AM', '9:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (36, 'Dickens and Sons', 'Mników', 68, '9:33 AM', '8:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (37, 'Nitzsche and Sons', 'Jingyang', 73, '8:00 AM', '9:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (38, 'Smith, Kuvalis and Crist', 'Outlook', 37, '8:14 AM', '9:44 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (39, 'Stamm, Von and Gibson', 'Xiakou', 50, '8:19 AM', '8:56 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (40, 'Toy Group', 'Kungur', 66, '8:11 AM', '8:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (41, 'Auer-O''Keefe', 'Sivers’k', 88, '8:52 AM', '8:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (42, 'Shanahan-Donnelly', 'Senadan', 29, '8:09 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (43, 'Kuhlman, Sporer and Aufderhar', 'Setonokalong', 81, '9:59 AM', '9:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (44, 'Rodriguez LLC', 'Kutapanjang', 54, '9:06 AM', '8:57 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (45, 'Gutmann, Runolfsdottir and Roberts', 'Lixi', 39, '9:53 AM', '8:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (46, 'Maggio Group', 'Amuru', 30, '8:44 AM', '8:31 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (47, 'Cruickshank Inc', 'Sukojember', 99, '9:25 AM', '9:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (48, 'Legros-Gleason', 'Litian', 8, '8:56 AM', '9:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (49, 'Jenkins, Daniel and Kuhlman', 'Santo Niño', 43, '8:58 AM', '8:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (50, 'Bayer, Langosh and Champlin', 'Châtillon', 73, '8:22 AM', '8:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (51, 'Smith and Sons', 'Hengjie', 33, '9:39 AM', '8:50 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (52, 'Daniel-Zboncak', 'Pustá Polom', 94, '9:44 AM', '9:48 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (53, 'Russel-Kuhn', 'Lille', 68, '8:36 AM', '8:31 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (54, 'Leffler-Fritsch', 'Nurlat', 99, '9:47 AM', '8:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (55, 'Franecki Group', 'Chakari', 41, '8:07 AM', '8:48 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (56, 'Larkin and Sons', 'Huaqiao', 12, '8:31 AM', '9:08 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (57, 'Pacocha, Konopelski and Little', 'Sumpur Kudus', 88, '9:29 AM', '8:56 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (58, 'Steuber and Sons', 'Évreux', 38, '8:23 AM', '8:52 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (59, 'Parker-Conroy', 'Mem Martins', 63, '8:03 AM', '8:02 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (60, 'Macejkovic, Morissette and Rutherford', 'Pomerode', 92, '9:56 AM', '9:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (61, 'Ledner-Lesch', 'Dulce Nombre de Culmí', 75, '9:26 AM', '9:03 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (62, 'O''Conner-Hudson', 'Maralal', 15, '9:52 AM', '8:45 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (63, 'Bartell-Harber', 'Verrettes', 69, '8:40 AM', '8:43 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (64, 'VonRueden Group', 'Alburitel', 16, '8:39 AM', '9:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (65, 'Stanton, O''Keefe and Streich', 'Batouri', 4, '9:19 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (66, 'Herzog Group', 'Balitai', 73, '8:31 AM', '8:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (67, 'Gottlieb LLC', 'Stari Grad', 70, '9:53 AM', '9:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (68, 'Quitzon, Gleason and Pouros', 'Kertabumi', 74, '8:21 AM', '8:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (69, 'Predovic, Dibbert and Leuschke', 'Vitry-sur-Seine', 84, '9:13 AM', '8:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (70, 'Daniel Group', 'Ōdachō-ōda', 6, '8:02 AM', '9:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (71, 'Tremblay, DuBuque and Bernier', 'Casal', 95, '9:09 AM', '8:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (72, 'Becker, Champlin and Koss', 'Zheleznodorozhnyy', 42, '9:52 AM', '9:13 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (73, 'Stoltenberg, Kulas and Kemmer', 'Floirac', 82, '9:39 AM', '9:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (74, 'Lesch-VonRueden', 'København', 81, '8:03 AM', '9:40 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (75, 'Witting, Gottlieb and Lowe', 'Novotroitsk', 50, '9:55 AM', '8:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (76, 'Upton Group', 'Santo André', 8, '8:42 AM', '9:14 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (77, 'Weissnat and Sons', 'Ystad', 76, '9:35 AM', '8:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (78, 'Sawayn LLC', 'Sakété', 40, '9:53 AM', '8:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (79, 'Schulist, Morissette and Torphy', 'Saint-Constant', 14, '8:37 AM', '8:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (80, 'Crona, Pfannerstill and Reichert', 'Chencun', 76, '9:07 AM', '9:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (81, 'Runolfsson, Schumm and Doyle', 'Qal‘ah-ye Na‘īm', 79, '8:03 AM', '8:26 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (82, 'Erdman-Schaefer', 'Biyan', 82, '9:04 AM', '9:57 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (83, 'Murray, Huel and Stoltenberg', 'Bulbul', 19, '9:44 AM', '9:44 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (84, 'Klocko, Kunde and Satterfield', 'Khemarat', 10, '9:45 AM', '8:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (85, 'Herman, Kirlin and MacGyver', 'Davila', 85, '9:23 AM', '9:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (86, 'Predovic, Ankunding and Rau', 'Nishinomiya-hama', 94, '9:22 AM', '8:14 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (87, 'Lesch Group', 'Umanday Centro', 72, '9:25 AM', '8:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (88, 'Skiles Group', 'Xarag', 89, '8:52 AM', '9:27 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (89, 'Greenfelder, Kassulke and Barrows', 'Extrema', 66, '9:58 AM', '8:31 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (90, 'Rogahn, Koelpin and Boyer', 'Ängelholm', 7, '8:53 AM', '9:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (91, 'Thiel-Abbott', 'Baluk', 1, '8:27 AM', '9:19 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (92, 'Borer, Rau and Ziemann', 'Wielbark', 63, '8:53 AM', '8:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (93, 'Hermann, Koch and Farrell', 'Picungbera', 46, '9:32 AM', '9:39 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (94, 'Waelchi, Hegmann and Nienow', 'Santa Maria', 45, '8:27 AM', '8:43 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (95, 'Christiansen Group', 'Mapinrea', 29, '9:02 AM', '9:35 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (96, 'Kihn, Krajcik and Kuvalis', 'Phatthaya', 98, '8:39 AM', '8:05 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (97, 'Conroy Group', 'Gyamco', 91, '8:32 AM', '8:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (98, 'Jast, Trantow and Turcotte', 'Malianchuan', 75, '8:02 AM', '9:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (99, 'Farrell-Fay', 'Calbuco', 100, '9:22 AM', '9:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (100, 'Champlin LLC', 'Neni', 66, '9:18 AM', '9:35 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (101, 'Bauch, Abshire and Stark', 'Orlová', 32, '9:31 AM', '8:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (102, 'McKenzie-Rohan', 'Nanto-shi', 83, '8:55 AM', '9:43 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (103, 'Mraz-Feeney', 'Meiktila', 99, '9:01 AM', '9:02 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (104, 'Waters-Kozey', 'Villa Dolores', 62, '9:50 AM', '8:01 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (105, 'Dooley, Beahan and Lueilwitz', 'Anmore', 11, '9:09 AM', '8:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (106, 'Murray, Purdy and Mills', 'La Soledad', 91, '8:11 AM', '8:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (107, 'Walker, Christiansen and Spencer', 'Zhangpu', 3, '8:58 AM', '8:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (108, 'Davis, Collins and Schroeder', 'Benzilan', 96, '8:59 AM', '8:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (109, 'Christiansen, Fritsch and Labadie', 'Gaojimiao', 71, '9:59 AM', '8:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (110, 'Brakus-Becker', 'Xinfa', 9, '8:13 AM', '8:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (111, 'Ullrich-Bahringer', 'Jatiklampok', 92, '8:09 AM', '8:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (112, 'Willms-Wyman', 'Banjar Mambalkajanan', 65, '8:02 AM', '9:19 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (113, 'Wuckert, Braun and Wiegand', 'Mirkovci', 38, '9:59 AM', '9:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (114, 'Brakus LLC', 'Cacheu', 89, '9:56 AM', '9:39 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (115, 'Bailey-Reinger', 'Naha-shi', 12, '9:56 AM', '9:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (116, 'Sauer and Sons', 'Ash Shuqayrah', 93, '9:36 AM', '9:58 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (117, 'Bailey-Parisian', 'Avignon', 61, '9:05 AM', '8:44 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (118, 'Fadel-Dach', 'Luena', 4, '9:53 AM', '8:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (119, 'Funk Group', 'Dahe', 92, '8:29 AM', '8:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (120, 'Leannon-Kerluke', 'Gaoping', 63, '9:25 AM', '9:07 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (121, 'Smith, Hilll and Bauch', 'Shimen', 84, '9:17 AM', '9:33 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (122, 'Stokes-Barrows', 'Louisville', 10, '9:51 AM', '9:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (123, 'Strosin LLC', 'Kokembang', 9, '9:06 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (124, 'Blanda, Johnson and Thiel', 'Älvängen', 73, '9:35 AM', '8:32 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (125, 'Pollich-Rodriguez', 'Dzyatlava', 17, '8:30 AM', '9:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (126, 'Kassulke-Collier', 'Paris 18', 62, '9:39 AM', '9:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (127, 'Morar, Heller and Wyman', 'Täby', 32, '9:14 AM', '8:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (128, 'Anderson Inc', 'Liuzhi', 67, '8:36 AM', '9:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (129, 'Murray-Weimann', 'Daniëlskuil', 76, '8:47 AM', '8:43 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (130, 'Grady LLC', 'Dubovka', 71, '8:52 AM', '9:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (131, 'Kunze-White', 'Tamarindo', 43, '8:35 AM', '9:26 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (132, 'Marvin Inc', 'Cola', 47, '8:53 AM', '8:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (133, 'Moen Group', 'Lyubech', 71, '9:56 AM', '9:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (134, 'Nolan Group', 'Taoyuan', 62, '8:54 AM', '9:13 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (135, 'Dibbert, Purdy and Sawayn', 'Yushu', 37, '8:06 AM', '8:34 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (136, 'Lindgren Group', 'Nai Harn', 26, '9:02 AM', '8:56 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (137, 'Luettgen and Sons', 'Bayanaūyl', 87, '9:45 AM', '9:52 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (138, 'Corwin Inc', 'Shangmofang', 60, '9:14 AM', '8:32 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (139, 'Herman-Russel', 'Adtugan', 2, '8:42 AM', '8:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (140, 'Mohr Group', 'Havířov', 21, '8:46 AM', '9:50 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (141, 'Mayer Group', 'Yongxing Chengguanzhen', 98, '8:51 AM', '8:44 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (142, 'Runte-Marquardt', 'Lupon', 32, '9:58 AM', '8:52 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (143, 'Breitenberg Group', 'Şirrīn ash Shamālīyah', 75, '9:01 AM', '9:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (144, 'Mitchell-Ward', 'Erie', 69, '8:50 AM', '9:34 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (145, 'Paucek LLC', 'Kawaguchi', 24, '9:12 AM', '8:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (146, 'Romaguera and Sons', 'Inya', 95, '9:29 AM', '9:26 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (147, 'Miller LLC', 'Maddela', 69, '8:45 AM', '8:45 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (148, 'Gottlieb-Bahringer', 'Breda', 40, '8:53 AM', '9:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (149, 'Nicolas, Lemke and Runolfsdottir', 'Halmstad', 74, '9:54 AM', '8:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (150, 'Herman-Veum', 'Zhiqing Songduo', 78, '9:30 AM', '9:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (151, 'Zieme-Brekke', 'Jetaral', 57, '8:37 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (152, 'Metz LLC', 'Chanuman', 87, '8:10 AM', '8:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (153, 'Dibbert and Sons', 'Jetaral', 10, '9:06 AM', '9:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (154, 'Russel Inc', 'Tyvriv', 80, '9:14 AM', '8:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (155, 'Kerluke, Howell and Rowe', 'Sang-e Māshah', 25, '8:28 AM', '8:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (156, 'Terry and Sons', 'Bukavu', 25, '9:19 AM', '9:24 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (157, 'Wisoky LLC', 'Kumla', 98, '9:23 AM', '8:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (158, 'Schuppe, Daugherty and Doyle', 'El Obeid', 90, '8:20 AM', '8:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (159, 'Schultz, Rempel and Altenwerth', 'Tall Abyaḑ', 54, '8:15 AM', '8:24 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (160, 'Nicolas, Mayert and Wolff', 'Yunxi', 9, '9:43 AM', '8:19 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (161, 'Ernser Inc', 'Barili', 46, '8:56 AM', '9:35 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (162, 'Hammes, Ferry and Lang', 'Daming', 78, '9:40 AM', '8:01 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (163, 'Hane-Bruen', 'Nam Khun', 29, '9:16 AM', '8:45 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (164, 'Prosacco, Fay and Collier', 'Héroumbili', 28, '8:04 AM', '8:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (165, 'Kertzmann, Kiehn and Glover', 'Monte Aprazível', 82, '8:47 AM', '9:19 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (166, 'D''Amore and Sons', 'Krasiczyn', 31, '8:30 AM', '9:38 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (167, 'O''Connell, Schamberger and Schmitt', 'Umm al Qaywayn', 25, '8:47 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (168, 'Reynolds-Pfannerstill', 'Shilovo', 45, '8:46 AM', '8:10 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (169, 'Wintheiser Inc', 'Zhentian', 25, '9:17 AM', '8:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (170, 'Kemmer-Jakubowski', 'Rawaapu', 88, '9:41 AM', '9:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (171, 'Yost, Wisozk and Beier', 'Eindhoven', 92, '8:51 AM', '9:05 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (172, 'Leffler LLC', 'Changxi', 85, '9:58 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (173, 'Keebler, Olson and Buckridge', 'Yasynuvata', 46, '8:26 AM', '9:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (174, 'Schultz-Fritsch', 'Lishu', 34, '9:41 AM', '8:57 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (175, 'Borer-Swaniawski', 'Ōgaki', 64, '9:57 AM', '8:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (176, 'Frami, Wilkinson and Romaguera', 'Tshikapa', 9, '8:08 AM', '9:02 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (177, 'Legros LLC', 'Umuarama', 92, '9:57 AM', '8:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (178, 'DuBuque, Christiansen and Prohaska', 'Santo Niño', 26, '9:45 AM', '9:40 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (179, 'Kuphal-Gulgowski', 'Xia’ertai', 32, '9:19 AM', '9:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (180, 'Langosh-Morar', 'Bezenchuk', 8, '9:21 AM', '9:52 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (181, 'Ankunding-Williamson', 'Łubnice', 46, '8:53 AM', '9:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (182, 'Cassin Group', 'Stamáta', 48, '9:26 AM', '8:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (183, 'Schultz, MacGyver and Parker', 'Zdíkov', 61, '8:53 AM', '9:08 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (184, 'Sawayn and Sons', 'Hesperange', 18, '9:13 AM', '8:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (185, 'Kutch-Marquardt', 'Niopanda', 59, '8:42 AM', '8:01 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (186, 'Treutel, Kassulke and Renner', 'Suidong', 82, '9:35 AM', '8:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (187, 'Zboncak-Kuvalis', 'Varberg', 13, '9:58 AM', '8:48 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (188, 'Hudson, Weimann and Ullrich', 'Straszydle', 6, '9:53 AM', '8:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (189, 'Kshlerin, D''Amore and Lockman', 'Colonia Catuete', 97, '9:42 AM', '9:20 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (190, 'O''Keefe, Conroy and Jacobson', 'Xin’andu', 30, '9:22 AM', '9:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (191, 'Sipes Group', 'Boliden', 98, '8:47 AM', '9:38 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (192, 'Conroy, Fay and Bernhard', 'Aix-en-Provence', 7, '9:59 AM', '8:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (193, 'Adams, Jacobs and Emard', 'Bobojong', 71, '9:35 AM', '8:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (194, 'Hickle, Carroll and Rippin', 'Margorejo', 33, '8:46 AM', '8:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (195, 'Douglas, Heaney and Casper', 'Waldbillig', 60, '8:46 AM', '9:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (196, 'Pagac-Ferry', 'Zargarān', 48, '9:37 AM', '9:45 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (197, 'Walker Group', 'Kukës', 93, '8:03 AM', '8:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (198, 'Green, Flatley and Krajcik', 'Vani', 94, '8:23 AM', '9:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (199, 'Purdy and Sons', 'Ostroróg', 53, '8:11 AM', '8:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (200, 'Stark-Wiegand', 'Liwan', 63, '9:47 AM', '8:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (201, 'Stroman-Ruecker', 'Nova Odesa', 77, '9:34 AM', '8:26 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (202, 'Cremin-Adams', 'São Julião do Tojal', 83, '8:02 AM', '9:34 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (203, 'Waelchi, Swaniawski and Stoltenberg', 'Qulaybīyah', 10, '8:09 AM', '9:52 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (204, 'Robel-Cormier', 'Xingfu', 14, '8:37 AM', '8:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (205, 'Hackett and Sons', 'Longwei', 30, '8:06 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (206, 'Goldner-Blick', 'Wolongquan', 95, '9:39 AM', '8:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (207, 'Feest-Cummerata', 'Herrán', 3, '8:52 AM', '8:42 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (208, 'Gottlieb, Funk and Bahringer', 'Gambēla', 81, '8:17 AM', '9:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (209, 'Kris and Sons', 'Parbatipur', 20, '9:32 AM', '8:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (210, 'O''Hara-Haag', 'Ferkessédougou', 77, '9:21 AM', '9:44 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (211, 'Hills, Schulist and Schoen', 'Jilib', 18, '8:19 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (212, 'Volkman and Sons', 'Fulu', 40, '9:29 AM', '9:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (213, 'Kunze, Lowe and Carter', 'Panggung', 32, '8:35 AM', '8:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (214, 'West Inc', 'Busilak', 90, '9:09 AM', '8:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (215, 'Doyle and Sons', 'Zuolan', 88, '9:48 AM', '9:58 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (216, 'Gutmann-Konopelski', 'Köneürgench', 79, '9:50 AM', '8:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (217, 'Simonis and Sons', 'Sokol', 19, '9:22 AM', '9:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (218, 'Gleichner and Sons', 'Xinpu', 96, '9:52 AM', '9:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (219, 'Willms LLC', 'Wrząsowice', 20, '8:49 AM', '9:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (220, 'Kling-Schuppe', 'Kribi', 99, '9:55 AM', '8:38 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (221, 'Kling Group', 'Skatepark', 1, '8:15 AM', '8:40 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (222, 'Deckow-Gulgowski', 'Shimen', 85, '8:46 AM', '9:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (223, 'Kuhn, Mitchell and Lemke', 'Valencia', 3, '8:52 AM', '9:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (224, 'VonRueden-Langworth', 'Capira', 73, '9:44 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (225, 'Lesch-Vandervort', 'Qinghaihu', 87, '9:13 AM', '8:38 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (226, 'Langworth LLC', 'Glugur Krajan', 45, '8:58 AM', '9:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (227, 'Pollich-Ferry', 'Celorico de Basto', 93, '8:14 AM', '9:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (228, 'Russel-Gorczany', 'Santa Ana', 42, '9:09 AM', '9:56 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (229, 'Rohan Group', 'Emmen', 77, '9:18 AM', '8:31 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (230, 'Boehm-Huels', 'Paôy Pêt', 79, '9:09 AM', '9:01 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (231, 'Bogisich LLC', 'Mukun', 80, '8:56 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (232, 'Howell Group', 'Kishiwada', 91, '8:20 AM', '8:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (233, 'Koss Group', 'Capim Grosso', 43, '9:14 AM', '8:14 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (234, 'Keebler-Steuber', 'Beni Khiar', 50, '9:06 AM', '9:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (235, 'Keebler, Rodriguez and VonRueden', 'Masipi West', 99, '8:42 AM', '9:45 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (236, 'Renner, Langosh and Carroll', 'Si Prachan', 52, '9:08 AM', '9:07 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (237, 'Hammes-Lynch', 'Veghel', 3, '9:25 AM', '9:58 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (238, 'Hand Inc', 'La Curva', 83, '8:04 AM', '9:13 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (239, 'MacGyver and Sons', 'Mabini', 29, '8:06 AM', '9:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (240, 'Schultz-Spencer', 'Wŏnsan', 62, '8:22 AM', '9:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (241, 'Dietrich Group', 'Acolla', 9, '8:03 AM', '8:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (242, 'Hermann LLC', 'Saint-Étienne', 75, '9:07 AM', '9:34 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (243, 'Hoeger, Quigley and Considine', 'Za‘tarah', 7, '8:09 AM', '8:33 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (244, 'Robel, Kunze and Weimann', 'Cortiçóis', 65, '8:28 AM', '9:44 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (245, 'Howe, Konopelski and Bins', 'Badajoz', 44, '9:26 AM', '8:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (246, 'Hintz-Johnston', 'Ḩammām Wāşil', 9, '9:51 AM', '9:02 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (247, 'Paucek Group', 'Baozi', 2, '9:00 AM', '8:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (248, 'Heathcote, Crist and Thiel', 'Yotsukaidō', 67, '8:16 AM', '9:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (249, 'Doyle and Sons', 'Portalegre', 16, '8:34 AM', '9:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (250, 'Hyatt LLC', 'Armenia', 41, '8:52 AM', '8:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (251, 'Spinka, Feeney and Stehr', 'Reston', 69, '9:02 AM', '8:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (252, 'Hamill Inc', 'Gueset', 89, '9:49 AM', '9:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (253, 'Schuppe-Kreiger', 'Lishu', 34, '9:30 AM', '8:40 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (254, 'McLaughlin-Hartmann', 'Sparwood', 55, '9:11 AM', '8:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (255, 'O''Hara, Volkman and Johnson', 'Marabá', 74, '9:19 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (256, 'Donnelly-Bayer', 'Maroantsetra', 7, '8:41 AM', '9:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (257, 'Ullrich and Sons', 'Gorbatov', 40, '8:36 AM', '9:05 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (258, 'Thiel LLC', 'Campos', 48, '8:32 AM', '9:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (259, 'Emard, Marquardt and Haag', 'Gatak', 90, '8:04 AM', '8:20 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (260, 'Mraz LLC', 'Jawl al Majma‘', 50, '9:48 AM', '8:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (261, 'Hammes, Rogahn and Dietrich', 'Tomilino', 97, '9:06 AM', '9:08 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (262, 'Kreiger, Nikolaus and Bruen', 'Stockholm', 20, '9:51 AM', '9:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (263, 'Jacobi, Wolf and Casper', 'Tshikapa', 12, '8:45 AM', '9:01 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (264, 'Boehm, Kemmer and Hegmann', 'Sadao', 74, '8:25 AM', '8:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (265, 'Boyle-Walker', 'Campanário', 86, '9:28 AM', '9:03 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (266, 'Koss-Lockman', 'Kokas', 27, '9:39 AM', '9:31 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (267, 'Adams Inc', 'Heshui', 87, '8:20 AM', '8:02 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (268, 'Lubowitz, Kris and Corkery', 'Na Chaluai', 42, '9:57 AM', '8:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (269, 'Kohler Inc', 'Sanski Most', 41, '8:05 AM', '9:32 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (270, 'Hoeger-Koch', 'Hualgayoc', 56, '9:38 AM', '9:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (271, 'Nienow Inc', 'Lisiy Nos', 55, '9:34 AM', '8:27 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (272, 'Stark, Abbott and Franecki', 'Rzhev', 30, '9:16 AM', '8:48 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (273, 'Pollich, Satterfield and Collins', 'Cayur', 38, '9:44 AM', '8:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (274, 'Welch and Sons', 'Sritanjung', 8, '8:45 AM', '8:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (275, 'Senger Inc', 'Limoges', 76, '8:57 AM', '8:07 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (276, 'Stanton Inc', 'Pizhanka', 43, '8:25 AM', '9:26 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (277, 'Feeney-Kunze', 'Bailingnao', 58, '8:13 AM', '9:50 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (278, 'Bayer Group', 'Velká Dobrá', 59, '8:30 AM', '9:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (279, 'Green, Murphy and Jenkins', 'Ambatondrazaka', 44, '9:21 AM', '9:13 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (280, 'Zemlak Inc', 'Lyon', 89, '9:13 AM', '8:04 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (281, 'Hoeger, Rodriguez and Schneider', 'Huantuo', 32, '9:42 AM', '8:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (282, 'King-Hermann', 'Hòa Bình', 76, '9:39 AM', '9:20 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (283, 'Dach-Willms', 'Tumbes', 81, '8:23 AM', '8:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (284, 'Jakubowski and Sons', '‘Alī al Gharbī', 81, '8:08 AM', '9:24 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (285, 'Kunde-Littel', 'Jubaoshan', 16, '9:39 AM', '9:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (286, 'Pfannerstill LLC', 'Monaghan', 57, '8:12 AM', '9:39 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (287, 'O''Conner Group', 'Estrela', 5, '9:12 AM', '9:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (288, 'Larson Inc', 'Huangguan', 70, '9:13 AM', '8:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (289, 'Dickinson, Kuphal and Trantow', 'Linqu', 55, '9:13 AM', '9:26 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (290, 'Ankunding-Kassulke', 'Olyshivka', 1, '9:35 AM', '9:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (291, 'Hudson, Moore and Hackett', 'Wāling', 97, '8:20 AM', '9:24 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (292, 'Bayer Inc', 'Porciúncula', 65, '8:27 AM', '9:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (293, 'Hackett Inc', 'Ipoh', 44, '8:40 AM', '9:27 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (294, 'Moore, Connelly and Balistreri', 'Wilmington', 44, '9:14 AM', '8:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (295, 'Klein LLC', 'Concepción del Uruguay', 93, '9:23 AM', '9:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (296, 'Huels, O''Conner and Block', 'Chapadinha', 97, '8:09 AM', '9:33 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (297, 'Thompson LLC', 'Cibuah', 52, '8:50 AM', '8:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (298, 'Leuschke-McGlynn', 'Banjar Beratan', 72, '8:07 AM', '9:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (299, 'Gerlach-McKenzie', 'Lyon', 76, '8:18 AM', '9:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (300, 'Balistreri-Botsford', 'Camp Ithier', 20, '9:39 AM', '9:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (301, 'Beier and Sons', 'Merkezköy', 96, '9:30 AM', '8:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (302, 'Corwin Inc', 'Mariara', 100, '9:27 AM', '9:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (303, 'Feil Group', 'Waigete', 99, '8:56 AM', '8:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (304, 'Roberts and Sons', 'Bularit', 93, '8:42 AM', '9:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (305, 'Bartell-Mohr', 'Makuyuni', 5, '8:34 AM', '9:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (306, 'Price, Paucek and Oberbrunner', 'Molteno', 22, '8:14 AM', '8:05 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (307, 'Bogan, Schowalter and Schuster', 'Šenčur', 81, '9:04 AM', '9:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (308, 'Schneider-Waelchi', 'Xiniu', 51, '8:35 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (309, 'Crona-Murray', 'Tuti', 9, '8:33 AM', '8:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (310, 'Towne and Sons', 'Baolong', 40, '9:53 AM', '8:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (311, 'Kuhic LLC', 'Bojen Kulon', 92, '9:18 AM', '8:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (312, 'Osinski LLC', 'Unity', 82, '9:45 AM', '8:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (313, 'Pacocha Group', 'Baltimore', 41, '9:21 AM', '9:52 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (314, 'Predovic Group', 'Ribeira do Pombal', 68, '9:07 AM', '9:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (315, 'Gerhold and Sons', 'Pajapita', 78, '9:21 AM', '9:58 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (316, 'Rice-Hills', 'Kolonowskie', 81, '8:22 AM', '9:13 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (317, 'Jones LLC', 'Veracruz', 24, '8:18 AM', '9:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (318, 'Aufderhar, Nitzsche and Willms', 'Druya', 61, '9:16 AM', '8:03 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (319, 'Buckridge Inc', 'Boston', 34, '8:18 AM', '8:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (320, 'Collins, Dooley and Corwin', 'Umeå', 19, '9:31 AM', '8:52 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (321, 'Marquardt, Mosciski and Smitham', 'Kakhovka', 96, '9:03 AM', '9:07 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (322, 'Schoen, Kling and Braun', 'Umanggudang', 42, '8:34 AM', '9:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (323, 'Sanford LLC', 'Longtian', 8, '9:58 AM', '8:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (324, 'Kohler, Sawayn and Turner', 'Tignapalan', 54, '9:24 AM', '9:20 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (325, 'Streich Inc', 'La Quebrada', 63, '8:11 AM', '8:39 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (326, 'Mayer-McClure', 'Kyaikkami', 96, '9:32 AM', '8:32 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (327, 'Connelly-Sawayn', 'Aroa', 69, '9:47 AM', '9:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (328, 'Treutel, Ferry and Fritsch', 'Xianyang', 78, '8:21 AM', '9:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (329, 'Fritsch-Paucek', 'Żórawina', 38, '9:12 AM', '9:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (330, 'Kshlerin Inc', 'Brinkmann', 90, '8:04 AM', '8:58 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (331, 'Koepp Inc', 'Qinghe', 67, '8:10 AM', '8:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (332, 'Feeney, Dickinson and Mayert', 'Cimara', 92, '9:13 AM', '9:31 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (333, 'Moen-Williamson', 'Akim Swedru', 57, '8:50 AM', '8:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (334, 'Jacobi-Flatley', 'Oke Mesi', 8, '8:59 AM', '9:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (335, 'Howe-Spinka', 'Piru', 47, '8:26 AM', '9:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (336, 'Oberbrunner-Herzog', 'Tengjia', 9, '8:05 AM', '9:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (337, 'Waters Inc', 'Karadaglije', 29, '9:32 AM', '8:08 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (338, 'Hackett LLC', 'Drohiczyn', 68, '9:03 AM', '9:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (339, 'Orn, Wyman and Miller', 'Skópelos', 40, '8:26 AM', '8:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (340, 'Lockman-Streich', 'Usuki', 93, '8:30 AM', '9:43 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (341, 'McKenzie-Frami', 'Baltimore', 7, '9:37 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (342, 'Hand, Kiehn and O''Reilly', 'Dao’er', 13, '9:42 AM', '9:26 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (343, 'Schowalter LLC', 'Bengga', 71, '8:33 AM', '8:05 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (344, 'Bogan, Hickle and Rodriguez', 'Arlington', 28, '9:02 AM', '9:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (345, 'Grant Inc', 'Timba Timuk', 68, '9:30 AM', '8:32 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (346, 'Raynor Group', 'Jiazhuang', 83, '8:26 AM', '8:39 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (347, 'Lakin-Tromp', 'Şūrān', 38, '8:18 AM', '8:48 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (348, 'Shanahan Inc', 'Koppies', 57, '8:48 AM', '8:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (349, 'Klocko-Kuvalis', 'Syevyerodonets’k', 28, '8:54 AM', '8:42 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (350, 'Schmeler Group', 'Luhyny', 46, '8:58 AM', '9:40 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (351, 'Shanahan-Schumm', 'Parnamirim', 19, '9:19 AM', '9:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (352, 'Beahan Group', 'Jinqiao', 47, '8:04 AM', '8:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (353, 'Hermann-Osinski', 'Zaoshi', 63, '8:50 AM', '8:43 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (354, 'Wisozk, Mayer and Boehm', 'Pobral', 24, '8:36 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (355, 'Purdy-Turner', 'Rumburk', 69, '8:28 AM', '8:38 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (356, 'Homenick-Krajcik', 'Enköping', 33, '9:41 AM', '9:35 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (357, 'Feil LLC', 'Grimshaw', 57, '9:21 AM', '8:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (358, 'Ruecker-Blick', 'Kolochava', 66, '8:15 AM', '8:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (359, 'Swaniawski-Pollich', 'Jieguanting', 86, '8:50 AM', '9:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (360, 'Kohler and Sons', 'Gaoyi', 36, '8:53 AM', '8:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (361, 'Frami and Sons', 'El Hatillo', 82, '9:50 AM', '9:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (362, 'McDermott-Weber', 'Goshogawara', 2, '8:36 AM', '9:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (363, 'Hayes and Sons', 'Dallas', 72, '9:21 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (364, 'Kautzer-Aufderhar', 'Kombapari', 13, '8:03 AM', '8:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (365, 'Schowalter, Doyle and Corwin', 'Az Zabadānī', 91, '8:43 AM', '9:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (366, 'Weber, Rowe and Maggio', 'West Palm Beach', 38, '8:47 AM', '8:04 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (367, 'Hayes, Goldner and Towne', 'Yunfeng', 69, '8:37 AM', '9:07 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (368, 'Wiegand LLC', 'Semibratovo', 85, '8:22 AM', '8:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (369, 'Runolfsson, Green and Wiza', 'Calingcuan', 21, '8:41 AM', '9:50 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (370, 'Brown and Sons', 'Zhongxinqiao', 90, '9:30 AM', '8:02 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (371, 'Mosciski-Considine', 'Zagreb', 69, '9:08 AM', '9:24 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (372, 'Adams-Haag', 'Butwāl', 84, '9:15 AM', '8:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (373, 'Purdy, Homenick and Paucek', 'Şaydnāyā', 68, '8:42 AM', '9:02 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (374, 'Fadel-Rau', 'Thị Trấn Bắc Yên', 16, '8:53 AM', '9:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (375, 'Bernhard, Abernathy and Williamson', 'Semamung', 72, '9:25 AM', '8:20 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (376, 'Conn, Runte and Romaguera', 'Lis', 77, '8:55 AM', '9:46 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (377, 'Shields and Sons', 'Az Zuwaytīnah', 27, '8:43 AM', '9:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (378, 'Lueilwitz-Monahan', 'Gonghe', 22, '8:41 AM', '9:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (379, 'Schowalter and Sons', 'Guadalupe', 44, '8:35 AM', '8:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (380, 'Hartmann, Jaskolski and Fisher', 'Kolchikón', 86, '9:46 AM', '8:48 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (381, 'Bruen-Halvorson', 'Houbai', 34, '9:25 AM', '8:20 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (382, 'Lind, Beer and Quigley', 'Xinyi', 75, '9:07 AM', '9:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (383, 'O''Reilly, Torphy and Cummings', 'Wyszków', 14, '9:04 AM', '8:58 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (384, 'Kiehn Group', 'Taiping', 77, '8:26 AM', '8:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (385, 'Ernser LLC', 'Al Khawkhah', 88, '8:23 AM', '8:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (386, 'Jacobi-Wolff', 'Chotcza', 68, '8:44 AM', '9:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (387, 'Moore-Herman', 'Solec-Zdrój', 24, '9:23 AM', '8:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (388, 'Thiel Group', 'Changwon', 7, '9:12 AM', '8:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (389, 'Koch-Ziemann', 'Sijunjung', 87, '8:02 AM', '9:10 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (390, 'Nicolas-Ferry', 'Shanggu', 86, '8:48 AM', '8:13 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (391, 'Daniel LLC', 'Sūq ar Rabū‘', 80, '8:48 AM', '8:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (392, 'Schinner LLC', 'Jorochito', 13, '9:07 AM', '9:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (393, 'Quigley and Sons', 'Mueang Suang', 25, '9:07 AM', '8:48 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (394, 'Brakus and Sons', 'Vardenik', 98, '8:56 AM', '8:42 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (395, 'Zemlak and Sons', 'Citeguh', 50, '9:00 AM', '8:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (396, 'Cartwright, Parker and Bashirian', 'Guanyao', 30, '9:39 AM', '9:51 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (397, 'Collins Inc', 'Ferraz de Vasconcelos', 11, '8:32 AM', '9:42 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (398, 'Baumbach LLC', 'Nankou', 23, '8:28 AM', '8:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (399, 'Lehner, Smitham and Pacocha', 'Mtsensk', 98, '8:54 AM', '8:23 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (400, 'Tillman Inc', 'Kihurio', 38, '8:36 AM', '9:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (401, 'Zemlak Group', 'Uvarovo', 39, '9:25 AM', '8:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (402, 'Kautzer-Conroy', 'Guantouzui', 51, '9:21 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (403, 'Streich-Jacobi', 'Pandansari', 3, '8:07 AM', '8:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (404, 'Hackett-Klein', 'Chelles', 29, '8:13 AM', '9:39 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (405, 'Conroy, Schumm and Parker', 'Chełmiec', 62, '8:36 AM', '9:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (406, 'Mann-Langosh', 'Kadipaten', 91, '9:43 AM', '9:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (407, 'Olson and Sons', 'Pulau Pinang', 32, '8:06 AM', '9:06 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (408, 'Durgan, Hane and Balistreri', 'Lagoa Vermelha', 78, '8:25 AM', '9:31 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (409, 'Pagac-Walsh', 'Vales', 85, '9:40 AM', '8:58 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (410, 'Nolan LLC', 'Sinhyeon', 90, '9:50 AM', '9:12 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (411, 'Bruen Group', 'Los Ángeles', 38, '8:26 AM', '9:57 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (412, 'Marquardt-Raynor', 'Carvalhal Redondo', 3, '8:28 AM', '9:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (413, 'Fritsch, Leannon and Hegmann', 'Juru', 43, '8:24 AM', '8:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (414, 'Nitzsche Group', 'Lilla Edet', 25, '8:27 AM', '8:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (415, 'Doyle LLC', 'Retorta', 71, '8:43 AM', '9:48 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (416, 'Weissnat, Schultz and Gerhold', 'Xilian', 32, '9:07 AM', '8:19 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (417, 'Frami, Schaefer and Kutch', 'Jiujiang', 55, '8:43 AM', '9:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (418, 'Russel, Ledner and Lubowitz', 'Kuala Lumpur', 55, '9:53 AM', '9:04 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (419, 'Connelly Group', 'Valvedditturai', 26, '9:54 AM', '8:14 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (420, 'Carroll and Sons', 'Sukaraharja', 10, '9:24 AM', '9:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (421, 'Labadie-Streich', 'Nanmuping', 64, '8:33 AM', '9:21 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (422, 'Kulas, Gutmann and Franecki', 'Jardim', 64, '9:02 AM', '9:45 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (423, 'Dickens, Hermiston and Trantow', 'Zhlobin', 74, '9:02 AM', '8:13 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (424, 'Leannon LLC', 'San Roque', 92, '9:11 AM', '8:02 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (425, 'Cartwright Group', 'Mae Hi', 22, '8:18 AM', '8:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (426, 'Quitzon Inc', 'Västerås', 31, '8:14 AM', '8:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (427, 'Jast, Treutel and Walsh', 'Phù Mỹ', 20, '9:35 AM', '9:10 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (428, 'Veum, Barrows and Kuhic', 'Kaliuling', 63, '8:03 AM', '9:35 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (429, 'Wuckert-Halvorson', 'Batsari', 42, '9:16 AM', '9:25 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (430, 'Kassulke-Armstrong', 'El Ocotón', 87, '8:23 AM', '8:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (431, 'Corwin Group', 'Albania', 25, '9:58 AM', '9:45 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (432, 'Gibson Group', 'Nueva Gorgona', 18, '9:40 AM', '8:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (433, 'Tremblay, Cole and Rohan', 'Tarrafal', 66, '9:00 AM', '8:50 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (434, 'Mayert and Sons', 'Chimichagua', 73, '8:49 AM', '9:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (435, 'Miller, Schneider and Ritchie', 'Kurmuk', 89, '9:41 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (436, 'Spinka, Marquardt and Hansen', 'Vychegodskiy', 91, '8:00 AM', '8:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (437, 'Mohr-Leffler', 'Naifalo', 55, '8:27 AM', '9:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (438, 'Murray-VonRueden', 'Kebon', 84, '8:00 AM', '9:05 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (439, 'Rau Group', 'Padurung', 19, '9:04 AM', '8:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (440, 'Rohan, Casper and Bradtke', 'Uhryniv', 85, '8:48 AM', '8:03 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (441, 'Tromp-Batz', 'Cabitan', 61, '9:01 AM', '9:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (442, 'Dare, Gleichner and Boyer', 'Kingston', 71, '8:59 AM', '9:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (443, 'Schaden, Kassulke and Shields', 'Detroit', 10, '9:08 AM', '8:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (444, 'Gibson-Simonis', 'Stalowa Wola', 3, '9:43 AM', '9:11 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (445, 'Crooks, Parisian and Kulas', 'Lindavista', 39, '8:18 AM', '8:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (446, 'Stanton LLC', 'København', 51, '8:22 AM', '8:26 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (447, 'MacGyver, Welch and Padberg', 'Wangchang', 99, '9:21 AM', '9:15 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (448, 'Larkin-O''Keefe', 'Minneapolis', 83, '9:39 AM', '8:37 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (449, 'Koss and Sons', 'Portela', 59, '9:22 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (450, 'Kovacek LLC', 'Vyritsa', 38, '9:34 AM', '8:44 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (451, 'Willms-Emmerich', 'Lyubokhna', 34, '9:49 AM', '9:38 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (452, 'Quigley and Sons', 'Tafo', 93, '8:41 AM', '8:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (453, 'Brown, Barrows and Volkman', 'Lapuan', 99, '9:51 AM', '9:56 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (454, 'Macejkovic-Heathcote', 'Staroshcherbinovskaya', 19, '9:29 AM', '9:59 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (455, 'Braun-Macejkovic', 'Cangkringan', 99, '9:55 AM', '9:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (456, 'Hammes Group', 'Dazaifu', 96, '8:14 AM', '9:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (457, 'Feeney, Effertz and O''Kon', 'Alvide', 65, '9:50 AM', '8:24 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (458, 'Schuster Group', 'La Poma', 58, '9:21 AM', '8:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (459, 'Becker Inc', 'Delft', 92, '9:32 AM', '8:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (460, 'Leannon, Dibbert and Collier', 'Novo Hamburgo', 72, '9:23 AM', '9:34 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (461, 'Quitzon, Jacobs and Koelpin', 'Cotovia', 71, '8:38 AM', '9:31 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (462, 'Kshlerin-Runte', 'Huruta', 97, '9:29 AM', '9:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (463, 'Romaguera, Champlin and Stanton', 'Mammari', 53, '8:16 AM', '8:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (464, 'Prosacco, Shanahan and Veum', 'Oviedo', 14, '8:09 AM', '8:56 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (465, 'Lubowitz and Sons', 'Supu', 92, '9:21 AM', '8:04 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (466, 'Torphy LLC', 'Yaruchel', 94, '8:53 AM', '9:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (467, 'Hoeger, Wehner and Spinka', 'Itaperuna', 23, '8:14 AM', '8:14 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (468, 'Hintz, Flatley and Kerluke', 'Ebene', 58, '9:25 AM', '8:17 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (469, 'Jones, Batz and Koss', 'Pniewy', 39, '8:05 AM', '9:47 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (470, 'Murazik, Bahringer and Hessel', 'Indianapolis', 100, '8:44 AM', '8:27 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (471, 'Satterfield, Schamberger and McCullough', 'Manna', 17, '9:28 AM', '8:34 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (472, 'Abernathy-Purdy', 'Poções', 29, '9:58 AM', '9:50 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (473, 'Hudson-Cummerata', 'Karanganyar', 6, '8:07 AM', '8:58 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (474, 'Mayert-Reichel', 'Oslo', 25, '8:06 AM', '8:43 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (475, 'Jacobs, Torp and Koch', 'Amsterdam Noord west', 95, '8:30 AM', '8:16 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (476, 'Zulauf LLC', 'Zambujal', 76, '8:52 AM', '8:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (477, 'Medhurst and Sons', 'Dongming', 30, '9:33 AM', '9:14 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (478, 'Sporer, Davis and Gutkowski', 'Gunan', 76, '9:39 AM', '8:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (479, 'Kozey and Sons', 'Tarikolot', 60, '8:36 AM', '9:56 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (480, 'Kozey-Lakin', 'Thành Phố Hà Giang', 25, '9:44 AM', '9:28 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (481, 'Yost-Dickinson', 'Dunaújváros', 18, '9:50 AM', '8:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (482, 'Wolff-Nolan', 'San Francisco de Macorís', 71, '8:07 AM', '9:32 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (483, 'Hahn-Schneider', 'Makoba', 85, '9:32 AM', '9:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (484, 'Kutch-Hudson', 'Chichibu', 36, '8:48 AM', '8:04 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (485, 'Tromp LLC', 'Barwałd Średni', 65, '8:44 AM', '8:49 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (486, 'Smith-Berge', 'Emiliano Zapata', 98, '8:15 AM', '8:29 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (487, 'Koelpin, Kub and Kovacek', 'Bodiosa a Velha', 14, '9:25 AM', '8:18 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (488, 'Torp LLC', 'Verkhniy Yasenov', 23, '8:38 AM', '8:01 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (489, 'Adams-Streich', 'Guanyinsi', 70, '9:18 AM', '8:00 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (490, 'Crist, Klocko and Hauck', 'Great Neck', 32, '9:48 AM', '9:53 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (491, 'Steuber-Feeney', 'Öndörhoshuu', 28, '8:14 AM', '9:09 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (492, 'Schowalter, Schimmel and Wiza', 'Stare Juchy', 52, '9:53 AM', '8:45 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (493, 'Feil, Okuneva and Mills', 'Dobrovo', 83, '8:18 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (494, 'Marks, Haag and Botsford', 'Fenkeng', 58, '9:27 AM', '9:22 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (495, 'Predovic, Wuckert and Gulgowski', 'Thanh Chương', 2, '8:18 AM', '8:36 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (496, 'Vandervort Group', 'Mankoeng', 43, '9:16 AM', '9:54 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (497, 'Bogisich and Sons', 'Lindavista', 4, '9:33 AM', '8:50 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (498, 'Fadel, Feil and Halvorson', 'Airuk', 25, '8:59 AM', '9:41 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (499, 'Trantow-Hirthe', 'Cisewu', 95, '8:04 AM', '8:55 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (500, 'Bokeria', 'Zagreb', 51, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (501, 'Apetit', 'Zagreb', 54, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (502, 'Bokamora', 'Zagreb', 67, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (503, 'ChopsGrill', 'Zagreb', 12, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (504, 'Paradiso', 'Zagreb', 77, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (505, 'Mignon', 'Zagreb', 99, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (506, 'Galija', 'Split', 19, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (507, 'Gust', 'Split', 24, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (508, 'Mama Bar', 'Split', 12, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (509, 'SpringWood', 'Split', 88, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (510, 'Lozo', 'Split', 7, '9:38 AM', '9:30 PM');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (511, 'Bistro Split', 'Split', 30, '08:00:00', '22:00:00');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (512, 'Dalmatian Delights', 'Split', 40, '09:00:00', '23:00:00');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (513, 'Pizzeria Zagreb', 'Zagreb', 35, '10:00:00', '21:00:00');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (514, 'Seafood Palace', 'Split', 50, '07:30:00', '22:30:00');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (515, 'Cevapi Corner', 'Rijeka', 20, '10:00:00', '20:00:00');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (516, 'Marmos', 'Split', 50, '07:30:00', '22:30:00');
insert into Restaurants (RestaurantId, Name, City, Capacity, OpeningHours, ClosingHours) values (517, 'Volat', 'Split', 50, '07:30:00', '22:30:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values (518, 'Sweet bites', 'Zagreb', 30, '08:00:00', '22:00:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values (519, 'Dessert heaven','Split', 40, '09:00:00', '23:00:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values (520, 'Bistro Cafe', 'Zagreb', 50, '08:00 AM', '10:00 PM');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(521, 'Restoran A', 'Zagreb', 50, '08:00', '22:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(522, 'Restoran B', 'Zagreb', 60, '09:00', '23:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(523, 'Restoran C', 'Rijeka', 40, '10:00', '21:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(524, 'Restoran D', 'Zagreb', 30, '07:00', '20:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(525, 'Restoran E', 'Rijeka', 70, '11:00', '00:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(526, 'Rijeka Bistro', 'Rijeka', 50, '08:00:00', '23:00:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(527, 'The Seaside Grill', 'Rijeka', 70, '10:00:00', '22:00:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(528, 'Rijeka Seafood', 'Rijeka', 40, '09:00:00', '21:00:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(529, 'Coastal Dining', 'Rijeka', 60, '07:00:00', '00:00:00');
insert into Restaurants (restaurantid, name, city, capacity, openinghours, closinghours) values(530, 'The Adriatic', 'Rijeka', 80, '12:00:00', '23:30:00');







