insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (1, 'Estell', 'Wallbutton', '1 Myrtle Trail', 59, 1627.26, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (2, 'Dalt', 'Lever', '1 Hanover Alley', 9, 1515.46, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (3, 'Rowena', 'Maskell', '3391 Schlimgen Parkway', 93, 1321.48, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (4, 'Lauree', 'Honywill', '44 Dunning Place', 35, 72.04, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (5, 'Lillian', 'Thickett', '6 Rowland Circle', 18, 1467.73, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (6, 'Miles', 'Tumility', '60 Towne Terrace', 99, 328.77, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (7, 'Bobine', 'Akred', '3870 Fair Oaks Parkway', 23, 789.19, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (8, 'Alfreda', 'Malley', '079 Jenna Way', 18, 1345.93, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (9, 'Sigfrid', 'Lingner', '156 Judy Alley', 93, 895.44, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (10, 'Yorke', 'Wallsworth', '88 Forest Dale Pass', 74, 458.29, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (11, 'Otto', 'Dring', '03 Stone Corner Hill', 77, 1236.33, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (12, 'Penni', 'Linklater', '12 Killdeer Terrace', 40, 1631.83, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (13, 'Selia', 'Brigden', '4 Truax Street', 6, 704.16, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (14, 'Betsey', 'Comettoi', '31343 Ohio Parkway', 22, 1061.35, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (15, 'Willi', 'Sykes', '66 Lerdahl Place', 66, 830.7, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (16, 'Glendon', 'Harvard', '7 Dottie Lane', 95, 651.12, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (17, 'Doreen', 'Dawtry', '46 Harper Park', 10, 1931.32, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (18, 'Michaella', 'Diben', '49337 Golf Course Center', 52, 316.25, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (19, 'Roberto', 'Artinstall', '086 Tennyson Trail', 64, 1521.5, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (20, 'Raddie', 'Tillerton', '81 Golf Course Trail', 86, 1306.07, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (21, 'Rikki', 'Eglington', '56414 Hintze Place', 25, 1257.36, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (22, 'Biddy', 'Sanper', '78683 Ilene Street', 6, 1688.13, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (23, 'Karon', 'Macias', '6516 Melody Hill', 16, 249.65, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (24, 'Adler', 'Giacovetti', '392 Norway Maple Crossing', 36, 692.67, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (25, 'Rosemarie', 'Fansy', '8 Golf Course Street', 81, 231.9, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (26, 'Anne', 'Sinnock', '81 Coleman Place', 50, 1579.36, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (27, 'Mariette', 'Allso', '211 Cherokee Court', 1, 708.68, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (28, 'Adena', 'Cheal', '93684 Dexter Parkway', 61, 1070.03, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (29, 'Nicki', 'Sheryne', '8848 Weeping Birch Plaza', 88, 486.01, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (30, 'Leonie', 'Alejandri', '81 Milwaukee Plaza', 85, 286.76, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (31, 'Jerry', 'Jeduch', '98870 Springs Avenue', 37, 59.01, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (32, 'Reeva', 'Masdon', '4860 Bonner Parkway', 81, 1575.99, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (33, 'Filide', 'Lomath', '414 Mockingbird Point', 71, 101.67, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (34, 'Dotty', 'Krystek', '5 Village Way', 43, 1018.23, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (35, 'Angelia', 'Spickett', '46498 Troy Parkway', 70, 1882.58, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (36, 'Cash', 'Thouless', '2901 Mayer Parkway', 33, 1898.66, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (37, 'Denver', 'Drieu', '2 Roth Court', 88, 692.5, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (38, 'Nicol', 'Akester', '2 Anhalt Place', 24, 943.36, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (39, 'Ronnie', 'Hankey', '2672 Meadow Valley Place', 57, 587.53, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (40, 'Diandra', 'Schnieder', '58 Esker Circle', 8, 1547.34, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (41, 'Bettina', 'Maslen', '0 Killdeer Center', 29, 1425.88, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (42, 'Malvin', 'Goody', '36 Armistice Plaza', 34, 35.17, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (43, 'Janine', 'Simeon', '73 Old Shore Alley', 20, 128.36, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (44, 'Missie', 'Carder', '78149 Heffernan Hill', 64, 950.72, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (45, 'Brew', 'Beebee', '7505 Harbort Crossing', 30, 1008.26, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (46, 'Erasmus', 'Sheen', '68593 Hauk Way', 47, 955.0, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (47, 'Ware', 'Piercy', '2779 Fremont Place', 57, 1970.8, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (48, 'Scot', 'Battman', '5 Porter Circle', 73, 242.59, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (49, 'Caresa', 'Demer', '848 Truax Drive', 68, 1567.7, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (50, 'Morena', 'M''cowis', '1 Bellgrove Street', 65, 339.5, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (51, 'Arthur', 'Mapston', '3 Fordem Park', 98, 778.47, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (52, 'Jed', 'Huccaby', '01 Farmco Terrace', 60, 1737.1, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (53, 'Anton', 'Moxom', '81019 Redwing Pass', 59, 164.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (54, 'Caty', 'Head', '9 Portage Alley', 26, 1692.21, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (55, 'Reube', 'Augustine', '3 Derek Avenue', 8, 844.48, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (56, 'Ingrid', 'Newstead', '51 Sycamore Park', 63, 1369.17, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (57, 'Iorgo', 'Spofforth', '73835 Gulseth Avenue', 59, 1693.01, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (58, 'Kinnie', 'Greetham', '5 Maple Wood Terrace', 20, 723.3, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (59, 'Maria', 'Wewell', '5 Scoville Street', 46, 1737.93, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (60, 'Judi', 'Hamilton', '52 Pawling Hill', 34, 779.78, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (61, 'Franklyn', 'Duddin', '32 Summerview Parkway', 26, 1820.54, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (62, 'Trista', 'Wildash', '280 David Trail', 68, 580.39, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (63, 'Birch', 'Gladding', '2 Sloan Trail', 50, 1701.13, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (64, 'Nerte', 'Handrock', '9808 Main Crossing', 22, 279.95, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (65, 'Crissy', 'Buss', '9 Sunbrook Park', 59, 553.75, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (66, 'Harlen', 'Dimitrie', '499 Iowa Place', 41, 1713.7, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (67, 'Ambur', 'Josipovitz', '82 Hayes Center', 60, 832.95, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (68, 'Cherianne', 'Bunting', '71 Darwin Hill', 53, 1507.91, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (69, 'Rebecca', 'Shaxby', '2 Lakeland Place', 44, 1138.7, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (70, 'Danette', 'Desport', '800 Ilene Drive', 35, 107.21, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (71, 'Cecelia', 'Isles', '87859 Leroy Lane', 18, 1799.53, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (72, 'Krystalle', 'Mccaull', '1 Macpherson Pass', 65, 1827.28, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (73, 'Genevieve', 'Jakubovski', '496 Thackeray Point', 29, 1318.55, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (74, 'Alonso', 'Toolin', '726 Vernon Terrace', 8, 1564.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (75, 'Terri', 'Licciardi', '39 Thierer Park', 53, 1340.8, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (76, 'Viki', 'Lismore', '94906 Memorial Place', 56, 998.95, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (77, 'Chery', 'Phette', '434 Maple Place', 19, 419.43, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (78, 'Mariele', 'MacMakin', '440 Memorial Hill', 41, 183.51, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (79, 'Cirillo', 'Wheildon', '36448 Annamark Junction', 27, 785.05, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (80, 'Janet', 'Macewan', '5860 Meadow Valley Point', 20, 866.6, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (81, 'Rick', 'Vannuchi', '5 Northwestern Circle', 59, 873.28, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (82, 'Clo', 'Cestard', '1224 3rd Avenue', 90, 486.49, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (83, 'Nikola', 'Sergent', '7568 Pearson Lane', 78, 650.39, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (84, 'Brod', 'Roddam', '917 Clove Road', 65, 1451.79, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (85, 'Georgianne', 'Allington', '12 Ramsey Drive', 39, 520.63, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (86, 'Ysabel', 'Schumacher', '194 Kingsford Place', 92, 1141.93, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (87, 'Ruben', 'Attrey', '3 Dennis Pass', 84, 1769.22, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (88, 'Lionello', 'Uren', '072 Harper Point', 73, 934.1, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (89, 'Melina', 'Corrado', '0220 Twin Pines Center', 9, 1174.49, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (90, 'Marsiella', 'Baddam', '04 Anzinger Trail', 41, 1873.22, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (91, 'Lynnelle', 'Capelen', '887 Sundown Place', 6, 1264.34, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (92, 'Stafford', 'Burdytt', '685 Barby Junction', 51, 920.27, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (93, 'Vivienne', 'Shills', '3 Alpine Way', 11, 1533.34, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (94, 'Lorilyn', 'Macieja', '9 Garrison Place', 58, 1136.98, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (95, 'Stanford', 'Kerr', '03585 2nd Road', 77, 603.86, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (96, 'Marian', 'Fritz', '8311 Mariners Cove Plaza', 53, 440.63, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (97, 'Adriane', 'Durker', '7183 Montana Junction', 4, 1572.24, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (98, 'Archie', 'Knotton', '3294 Bunker Hill Park', 86, 1718.89, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (99, 'Dimitry', 'Woolforde', '371 Manufacturers Circle', 31, 752.97, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (100, 'Mordecai', 'Stapels', '98 Erie Place', 56, 1084.83, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (101, 'Lothario', 'Vanyarkin', '97 Tomscot Pass', 74, 1134.05, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (102, 'Dalia', 'Sleany', '94985 Meadow Valley Street', 89, 1168.71, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (103, 'Henryetta', 'Meriot', '09154 Acker Avenue', 64, 126.29, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (104, 'Ardis', 'Cheetam', '52 Sunbrook Drive', 68, 1969.49, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (105, 'Delila', 'Dowyer', '11 Oak Valley Drive', 71, 849.24, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (106, 'Marinna', 'Craighall', '1793 Green Ridge Terrace', 16, 789.31, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (107, 'Adorne', 'Ruoss', '94086 Sunbrook Street', 40, 1179.42, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (108, 'Taber', 'Carlett', '77 Luster Pass', 44, 1215.87, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (109, 'Merrili', 'Beddoe', '51444 Dexter Place', 100, 534.81, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (110, 'Julianne', 'Label', '9 Bunker Hill Way', 68, 1634.04, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (111, 'Zaneta', 'Matokhnin', '974 Pankratz Court', 26, 1858.85, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (112, 'Juditha', 'Conahy', '5584 Green Place', 85, 649.88, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (113, 'Freida', 'Antoniottii', '29 Messerschmidt Terrace', 50, 1125.51, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (114, 'Bertie', 'Spong', '005 Crescent Oaks Way', 86, 623.33, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (115, 'Emmalyn', 'MacShane', '73 Farmco Junction', 76, 539.5, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (116, 'Elberta', 'Biggans', '55 Dakota Street', 23, 1310.03, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (117, 'Maximilien', 'Leas', '2 Jana Lane', 4, 317.43, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (118, 'Frederica', 'Bake', '55641 Vernon Avenue', 19, 1482.34, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (119, 'Yettie', 'Nellis', '1 Old Gate Trail', 35, 1564.46, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (120, 'Norina', 'Nye', '923 Lien Alley', 78, 1870.2, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (121, 'Klement', 'Dockwray', '121 Ohio Junction', 90, 389.59, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (122, 'Olive', 'Marklin', '717 Southridge Park', 46, 926.9, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (123, 'Wendye', 'Karslake', '9 Debs Terrace', 14, 1839.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (124, 'Ezri', 'McDill', '19 Sunnyside Terrace', 85, 1062.35, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (125, 'Artur', 'Kidston', '39 Pennsylvania Trail', 43, 1072.26, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (126, 'Gaylene', 'Rabier', '516 Barby Trail', 93, 1212.16, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (127, 'Leta', 'Markey', '804 Donald Park', 36, 1777.33, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (128, 'Hussein', 'MacCombe', '82 Mockingbird Park', 44, 1633.79, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (129, 'Tad', 'Kidde', '33643 Milwaukee Way', 58, 931.6, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (130, 'Gavrielle', 'Creavin', '4456 Northfield Way', 3, 1785.71, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (131, 'Arlen', 'Grayling', '99 Crowley Junction', 97, 1723.58, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (132, 'Malorie', 'Emtage', '3373 Hazelcrest Circle', 28, 1845.1, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (133, 'Zonda', 'Roth', '287 Drewry Plaza', 66, 141.8, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (134, 'Tonnie', 'Kuhnt', '02256 Bultman Center', 11, 1042.12, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (135, 'Gillian', 'Ekins', '4 Mallory Terrace', 69, 436.63, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (136, 'Zea', 'Whipple', '76 Mendota Way', 81, 140.72, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (137, 'Mayne', 'Yurin', '22 Caliangt Parkway', 65, 1899.53, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (138, 'Kennie', 'Vyvyan', '3753 Del Sol Lane', 21, 1641.66, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (139, 'Carrissa', 'Gleasane', '4 Weeping Birch Point', 63, 896.76, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (140, 'Ileana', 'Binford', '43127 Manufacturers Drive', 13, 520.84, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (141, 'Vinson', 'Bax', '5729 Meadow Vale Point', 27, 181.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (142, 'Allegra', 'Trippett', '75021 Washington Way', 49, 1649.32, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (143, 'Bev', 'Siseland', '24 Roth Circle', 13, 160.34, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (144, 'Jacky', 'Neilands', '92078 Clarendon Lane', 43, 1149.85, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (145, 'Hillary', 'Longfellow', '79703 Dovetail Hill', 47, 1634.38, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (146, 'Arline', 'Deyenhardt', '613 Vermont Point', 100, 118.03, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (147, 'Genna', 'Clewett', '1352 Starling Trail', 42, 386.93, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (148, 'Rupert', 'Calf', '55 Kings Point', 12, 1869.27, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (149, 'Inna', 'Chiles', '6 Pankratz Alley', 44, 85.84, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (150, 'Rebbecca', 'Casarini', '40844 Farwell Place', 90, 1737.72, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (151, 'Aurelie', 'MacRitchie', '8647 Spohn Plaza', 60, 247.87, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (152, 'Far', 'Prentice', '39465 Kennedy Way', 41, 433.84, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (153, 'Drusilla', 'Kerrod', '13 Beilfuss Street', 63, 573.1, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (154, 'Shell', 'Gartan', '23 Kipling Road', 77, 312.94, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (155, 'Ida', 'Kilbride', '4588 Bellgrove Alley', 12, 1113.21, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (156, 'Swen', 'Matiashvili', '0 Sutherland Plaza', 83, 1668.96, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (157, 'Lindsy', 'Shermore', '82128 Pierstorff Pass', 1, 801.89, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (158, 'Jyoti', 'Guidera', '1311 Utah Alley', 14, 374.08, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (159, 'Hagan', 'Starford', '5092 Sunnyside Alley', 28, 1359.54, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (160, 'Guillemette', 'Occleshaw', '3537 Aberg Center', 48, 585.87, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (161, 'Seymour', 'Forsdike', '66234 David Crossing', 94, 617.24, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (162, 'Yehudi', 'Brimson', '84179 Becker Way', 65, 1306.33, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (163, 'Alex', 'Sheardown', '339 Eastwood Pass', 18, 1235.33, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (164, 'Frannie', 'Moulds', '0 Vernon Avenue', 92, 921.35, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (165, 'Worden', 'Partridge', '5658 Village Parkway', 92, 1114.27, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (166, 'Carlene', 'Blincowe', '5 Farragut Crossing', 45, 127.26, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (167, 'Titus', 'Crumby', '84 Holy Cross Court', 55, 1384.17, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (168, 'Mac', 'Stiegars', '09 Straubel Center', 36, 68.88, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (169, 'Krystyna', 'Noto', '46198 Annamark Crossing', 61, 1886.29, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (170, 'Mirabelle', 'Skirling', '180 Granby Lane', 81, 500.1, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (171, 'Bengt', 'Grayshan', '9 Spaight Hill', 21, 646.58, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (172, 'Madella', 'Gridon', '1153 Cottonwood Way', 13, 1112.06, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (173, 'Alaine', 'Faber', '4 Fordem Parkway', 61, 584.06, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (174, 'Almeda', 'Leversha', '9832 Pearson Pass', 20, 1873.41, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (175, 'Diannne', 'Beek', '751 Independence Center', 22, 561.73, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (176, 'Quentin', 'Swinfen', '035 Browning Center', 5, 1158.84, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (177, 'Imelda', 'Celle', '3 Welch Circle', 95, 1511.55, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (178, 'Katheryn', 'MacGow', '11 Farwell Trail', 73, 99.47, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (179, 'Agna', 'Costan', '66638 Esker Alley', 72, 1247.8, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (180, 'Tamar', 'Cheshir', '14 Union Hill', 3, 1295.85, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (181, 'Hattie', 'Gillingwater', '74 Delladonna Crossing', 62, 114.93, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (182, 'Shermie', 'Chilles', '61547 4th Way', 82, 305.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (183, 'Erda', 'Garlinge', '9 3rd Court', 30, 1137.64, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (184, 'Beth', 'Jobling', '9137 Spohn Way', 2, 1325.19, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (185, 'Gaby', 'Glason', '04167 Hagan Place', 57, 47.02, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (186, 'Noah', 'Shaplin', '1 Nelson Alley', 88, 1585.78, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (187, 'Tedman', 'Sichardt', '8822 Bultman Hill', 13, 899.43, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (188, 'Joel', 'Goard', '75153 Eagan Court', 29, 61.74, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (189, 'Demetri', 'Smallthwaite', '5 Warrior Place', 29, 787.19, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (190, 'Peria', 'Test', '8790 Warrior Place', 9, 1509.98, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (191, 'Sander', 'Trowbridge', '3 Northfield Center', 49, 1376.46, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (192, 'Goldarina', 'Tozer', '02 Bayside Pass', 89, 1983.49, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (193, 'Tawnya', 'Mokes', '61 Dapin Road', 31, 626.76, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (194, 'Patrice', 'Bohlmann', '6060 Lakeland Lane', 20, 638.08, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (195, 'Lawton', 'De Caroli', '53228 Artisan Way', 19, 1450.29, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (196, 'Ulla', 'Tuffs', '31863 Marcy Park', 98, 1258.52, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (197, 'Shawn', 'Comello', '2 Hermina Crossing', 42, 901.42, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (198, 'Benedicto', 'Coucha', '57357 Alpine Hill', 31, 1766.8, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (199, 'Levy', 'De Dei', '4 Ludington Street', 1, 529.9, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (200, 'Sax', 'Kirmond', '6 Quincy Terrace', 35, 486.79, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (201, 'Kin', 'Engley', '3163 Dottie Center', 33, 1323.25, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (202, 'Berenice', 'Blackaller', '739 Johnson Way', 59, 1494.43, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (203, 'Guillaume', 'Knowler', '4 Banding Street', 55, 223.96, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (204, 'Tadeas', 'Slane', '76 Jenna Trail', 26, 1180.49, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (205, 'Maye', 'Beckerleg', '18446 Pearson Trail', 4, 811.27, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (206, 'Barny', 'Petre', '605 Red Cloud Drive', 79, 268.63, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (207, 'Ichabod', 'Crossthwaite', '23 American Ash Center', 66, 969.83, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (208, 'Farand', 'Ajean', '8 Bluejay Park', 83, 1678.97, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (209, 'Noll', 'Chaney', '80241 Marcy Way', 42, 1546.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (210, 'Natty', 'Sparrowe', '98 Hollow Ridge Pass', 67, 1369.11, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (211, 'Barth', 'Bilney', '1 Hauk Court', 84, 65.6, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (212, 'Ethelin', 'MacDiarmid', '17206 Transport Lane', 71, 1161.64, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (213, 'Bogey', 'Arlow', '57566 Westend Pass', 95, 762.63, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (214, 'Evonne', 'Oxx', '0534 Farwell Place', 83, 89.45, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (215, 'Dee', 'Bullivant', '972 Talmadge Hill', 52, 787.71, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (216, 'Xymenes', 'Hassard', '9555 Tennyson Lane', 99, 1689.22, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (217, 'Benedicta', 'Tart', '699 Meadow Valley Center', 26, 866.8, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (218, 'Bevvy', 'Tinsley', '99 Fairview Way', 11, 1881.77, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (219, 'Agneta', 'Drugan', '182 Duke Parkway', 89, 369.27, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (220, 'Susannah', 'Walcher', '88652 Ridge Oak Lane', 63, 1839.71, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (221, 'Hubey', 'Bremmer', '449 Brown Plaza', 39, 1451.9, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (222, 'Clement', 'Watsham', '0 Amoth Circle', 19, 208.76, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (223, 'Neal', 'Taberner', '36 Ramsey Center', 79, 804.86, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (224, 'Stacee', 'Manoch', '56572 Hansons Junction', 82, 29.69, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (225, 'Annissa', 'Beevors', '8720 Everett Street', 25, 1937.54, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (226, 'Edan', 'Oneile', '5229 Springs Crossing', 7, 1497.71, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (227, 'Jerrie', 'Golston', '843 Mendota Center', 92, 1667.18, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (228, 'Stevy', 'Vitall', '25 Nova Park', 55, 1716.22, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (229, 'Ileana', 'Cullotey', '438 Canary Avenue', 1, 741.53, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (230, 'Pasquale', 'Kermitt', '519 Cardinal Trail', 98, 1345.38, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (231, 'Hughie', 'Iapico', '20 David Point', 32, 1417.38, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (232, 'Ardelis', 'Searl', '2018 Cordelia Trail', 62, 799.97, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (233, 'Jami', 'Kochs', '5 Parkside Junction', 17, 1571.79, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (234, 'Ginnie', 'Buckell', '435 Bunting Parkway', 54, 1231.13, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (235, 'Bartram', 'Slavin', '6 Kensington Terrace', 19, 1929.07, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (236, 'Jacki', 'Gregg', '738 3rd Hill', 54, 672.87, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (237, 'Currey', 'Tregido', '74813 Longview Place', 8, 264.61, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (238, 'Lauri', 'Borthe', '60 Donald Court', 97, 1979.91, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (239, 'Alexina', 'Hollindale', '4579 Hollow Ridge Crossing', 65, 1440.53, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (240, 'Brooks', 'Feander', '84 Old Gate Plaza', 91, 706.88, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (241, 'Rabbi', 'Shave', '9277 Ilene Plaza', 22, 501.41, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (242, 'Cassandre', 'Criag', '641 Carpenter Plaza', 89, 1985.9, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (243, 'Aurlie', 'Loosemore', '893 Kenwood Junction', 74, 1067.7, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (244, 'Kahlil', 'Gallear', '8071 Boyd Parkway', 95, 768.41, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (245, 'Prudy', 'Skamell', '2 Weeping Birch Crossing', 18, 1002.45, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (246, 'Davide', 'Kelleway', '3 Montana Hill', 96, 1562.96, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (247, 'Corie', 'Dockrey', '1 Melody Terrace', 100, 1257.64, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (248, 'Ola', 'Hane', '3406 Sachs Court', 52, 31.06, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (249, 'Cammie', 'Locock', '9817 Homewood Place', 58, 1618.05, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (250, 'Marya', 'Hehl', '26 Lunder Drive', 41, 484.01, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (251, 'Thorndike', 'Neasam', '7872 Canary Parkway', 38, 1072.7, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (252, 'Earl', 'Stapleford', '5918 Kingsford Circle', 85, 1480.99, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (253, 'Rianon', 'Luckhurst', '72377 Nelson Parkway', 75, 949.77, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (254, 'Olav', 'Larmuth', '18529 Surrey Avenue', 85, 914.75, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (255, 'Doll', 'Pegrum', '68 Becker Pass', 13, 1488.34, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (256, 'Christiane', 'Coxhead', '9 Lighthouse Bay Hill', 59, 1694.67, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (257, 'Agnesse', 'Dymocke', '149 Eagle Crest Hill', 99, 631.71, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (258, 'Arly', 'Bricket', '83 Springview Crossing', 28, 1686.21, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (259, 'Zelig', 'Dring', '1 Mockingbird Center', 83, 570.96, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (260, 'Waylin', 'Stores', '01243 International Alley', 52, 1233.86, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (261, 'Caterina', 'Sawden', '2 Lake View Point', 45, 1914.36, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (262, 'Clarance', 'Marcone', '5 Scott Drive', 66, 1945.52, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (263, 'Yul', 'Meconi', '7 Homewood Road', 6, 844.32, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (264, 'Krishnah', 'Ivery', '3564 Pleasure Crossing', 1, 151.21, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (265, 'Ellette', 'Meaders', '918 Del Mar Junction', 56, 922.11, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (266, 'Eamon', 'Nellies', '424 Hoffman Point', 83, 525.2, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (267, 'Padgett', 'Ashbolt', '43 Norway Maple Trail', 40, 260.23, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (268, 'Kayley', 'O''Caherny', '6 Buhler Pass', 52, 1389.63, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (269, 'Jammie', 'O''Hickey', '8253 Mcbride Crossing', 28, 1003.39, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (270, 'Randolf', 'Kipling', '45 Crowley Plaza', 39, 1080.6, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (271, 'Miranda', 'McLafferty', '18 Lake View Hill', 58, 643.11, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (272, 'Bradley', 'Diego', '197 Daystar Plaza', 72, 376.06, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (273, 'Emerson', 'Richter', '928 Kropf Park', 78, 890.46, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (274, 'Jocelyn', 'Lamplough', '2982 Debra Circle', 14, 92.42, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (275, 'Rebe', 'Dillingstone', '857 Waywood Hill', 86, 1887.02, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (276, 'Marc', 'Huxtable', '2700 Merchant Parkway', 96, 1488.39, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (277, 'Barron', 'McKelvie', '9152 Anniversary Crossing', 36, 886.94, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (278, 'Archy', 'Causier', '14 Scoville Drive', 56, 1733.97, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (279, 'Basil', 'Bickford', '485 Scoville Terrace', 52, 1376.52, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (280, 'Andrus', 'MacEveley', '0 Barby Center', 27, 1721.46, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (281, 'Chic', 'Bartosinski', '66 Roth Road', 39, 971.23, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (282, 'Marijn', 'Twoohy', '9689 4th Point', 38, 1881.85, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (283, 'Shellysheldon', 'Butchers', '90 Sachtjen Park', 52, 1741.91, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (284, 'Rurik', 'Duthy', '18 Carpenter Park', 31, 1172.28, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (285, 'Bink', 'Staning', '51464 Almo Alley', 50, 1399.84, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (286, 'Roderich', 'Runnett', '6798 Commercial Way', 63, 1055.06, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (287, 'Guendolen', 'Hartington', '37979 Lake View Circle', 70, 814.2, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (288, 'Trstram', 'Reneke', '911 Ramsey Drive', 93, 334.01, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (289, 'Saunder', 'Dilley', '861 Redwing Drive', 26, 1187.94, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (290, 'Davidde', 'McGrorty', '0 Sundown Court', 45, 1663.95, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (291, 'Royal', 'Bracco', '803 Iowa Street', 54, 92.04, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (292, 'Pall', 'Castangia', '50 Dexter Center', 27, 1557.83, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (293, 'Beauregard', 'Behneke', '4 Farwell Hill', 70, 775.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (294, 'Drusilla', 'Beauman', '87 Springview Lane', 75, 1960.57, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (295, 'Ramona', 'Balchin', '5 Steensland Way', 11, 589.93, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (296, 'Charlene', 'Crommett', '474 Schlimgen Way', 27, 705.24, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (297, 'Pippo', 'Cannop', '32 Veith Hill', 24, 1726.17, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (298, 'Berky', 'Coll', '2603 Coleman Crossing', 18, 1392.53, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (299, 'Cam', 'Alexis', '6 Northfield Street', 59, 1088.8, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (300, 'Pandora', 'Restall', '05 Stephen Lane', 42, 422.45, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (301, 'Robbyn', 'Mews', '073 Nova Way', 25, 1157.08, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (302, 'Audrye', 'Exposito', '95444 Algoma Hill', 1, 41.52, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (303, 'Rodolphe', 'Cottom', '4 Farwell Pass', 13, 1134.15, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (304, 'Rodolphe', 'Brandoni', '60 Holy Cross Junction', 23, 1832.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (305, 'Lela', 'Larrat', '6 Farwell Road', 64, 1417.83, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (306, 'Tawnya', 'Oldfield', '1 Calypso Junction', 1, 1476.26, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (307, 'Maurizia', 'Van Rembrandt', '50390 Maywood Alley', 69, 512.93, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (308, 'Vernon', 'Bonder', '65943 Sommers Point', 17, 1681.22, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (309, 'Loleta', 'Dilgarno', '5 Sachs Court', 76, 1153.26, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (310, 'Gonzales', 'Bachellier', '50 Artisan Center', 25, 1494.05, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (311, 'Lanae', 'Cadany', '1008 Westridge Crossing', 90, 345.72, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (312, 'Chastity', 'Musk', '06828 Wayridge Alley', 6, 1212.76, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (313, 'Ambur', 'Bittlestone', '08941 Victoria Junction', 96, 156.68, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (314, 'Stanwood', 'Malthouse', '93 Stephen Lane', 26, 1775.35, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (315, 'Melisandra', 'Whitfeld', '54 Schmedeman Way', 21, 660.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (316, 'Pren', 'Ferreli', '738 Lukken Plaza', 14, 1828.71, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (317, 'Dukey', 'Samsin', '8932 Cody Crossing', 36, 1171.49, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (318, 'Edgar', 'Ewens', '5 Oriole Way', 24, 827.64, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (319, 'Tybie', 'Grieve', '5742 Glacier Hill Avenue', 21, 786.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (320, 'Kailey', 'Lux', '27731 Atwood Park', 2, 1553.38, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (321, 'Annemarie', 'Korneev', '610 Hudson Parkway', 18, 401.29, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (322, 'Kelly', 'Erbain', '4448 Amoth Alley', 46, 198.57, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (323, 'Ronda', 'Moon', '966 Muir Street', 84, 680.77, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (324, 'Susette', 'Deerness', '50 Cherokee Alley', 2, 1230.25, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (325, 'Kyla', 'Larwell', '11 Valley Edge Avenue', 98, 510.59, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (326, 'Cherri', 'Keble', '295 Barnett Parkway', 60, 1191.02, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (327, 'Cos', 'Drew', '74 Schlimgen Avenue', 48, 1377.17, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (328, 'Dana', 'Walkden', '2961 Anhalt Crossing', 22, 1737.18, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (329, 'Rosalia', 'Hannaway', '7 Dwight Point', 52, 1574.09, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (330, 'Ravi', 'Bettison', '3 Mifflin Street', 32, 693.45, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (331, 'Clayson', 'Note', '90685 5th Plaza', 83, 1766.62, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (332, 'Aleen', 'Kissock', '5587 Sage Center', 53, 161.03, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (333, 'Hobie', 'Lorenzin', '1 Chive Point', 92, 1343.53, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (334, 'Willi', 'Caine', '2753 Welch Drive', 10, 841.22, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (335, 'Bryce', 'Goutcher', '42 Cordelia Terrace', 23, 48.55, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (336, 'Bonny', 'Giovanazzi', '1438 Dayton Lane', 35, 1900.15, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (337, 'Jareb', 'Heading', '51212 Springview Road', 21, 1346.55, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (338, 'Corina', 'Alder', '94 Colorado Pass', 96, 656.44, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (339, 'Leyla', 'Shitliff', '51 Orin Pass', 57, 419.27, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (340, 'Ulrikaumeko', 'Dimitrie', '11944 Melby Road', 89, 1851.72, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (341, 'Dory', 'Burhouse', '07904 Manitowish Way', 39, 1211.77, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (342, 'Eugenie', 'McCauley', '683 Northport Drive', 96, 1913.13, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (343, 'Rena', 'Toulamain', '2 Buhler Plaza', 31, 608.81, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (344, 'Robbie', 'Coggill', '680 Homewood Avenue', 35, 1216.5, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (345, 'Britt', 'Audritt', '718 Cherokee Hill', 77, 781.02, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (346, 'Ashbey', 'Maud', '631 Heffernan Drive', 44, 586.58, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (347, 'Duff', 'Tasseler', '9 Commercial Junction', 16, 1543.1, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (348, 'Shurwood', 'Simonot', '69229 Moose Junction', 81, 293.02, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (349, 'Elvin', 'Yurevich', '60361 American Park', 35, 1527.78, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (350, 'Benny', 'Varsey', '30090 Oneill Plaza', 74, 1576.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (351, 'Murdoch', 'Jeanin', '5 Lyons Hill', 8, 385.03, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (352, 'Anders', 'McMurraya', '43 Jenifer Hill', 14, 952.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (353, 'Aveline', 'Kemmett', '4564 Park Meadow Lane', 66, 371.47, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (354, 'North', 'Bettis', '60848 Reinke Parkway', 20, 1973.4, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (355, 'Skelly', 'Hegg', '483 Vermont Court', 35, 1482.76, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (356, 'Chris', 'Costigan', '774 Elgar Junction', 5, 895.18, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (357, 'Hilario', 'Grewar', '1 Corscot Point', 21, 417.82, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (358, 'Nevil', 'Rusling', '85331 Coleman Road', 18, 809.77, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (359, 'Danny', 'Iskov', '3925 Hollow Ridge Center', 100, 432.19, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (360, 'Forest', 'Girling', '3 Ruskin Road', 74, 1628.97, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (361, 'Heloise', 'Kempson', '86 Homewood Way', 35, 459.6, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (362, 'Petronella', 'Grombridge', '45678 Russell Point', 92, 1269.34, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (363, 'Natala', 'Stut', '952 Randy Crossing', 31, 255.51, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (364, 'Livia', 'Erie', '07567 Bonner Plaza', 73, 1686.63, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (365, 'Eryn', 'Soppit', '74013 Forest Run Road', 58, 1204.57, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (366, 'Leanor', 'St Ange', '077 Butternut Junction', 56, 1950.03, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (367, 'Diann', 'Patters', '75465 Oriole Court', 74, 1153.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (368, 'Magdalen', 'Frude', '5 Evergreen Park', 35, 460.93, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (369, 'Renelle', 'Rieme', '4 Fordem Circle', 79, 216.81, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (370, 'Bendick', 'MacAne', '05908 Hanson Drive', 77, 1364.07, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (371, 'Waldemar', 'Dockray', '84434 Loeprich Court', 54, 1905.19, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (372, 'Phil', 'Braddick', '69 Bartelt Terrace', 10, 443.92, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (373, 'Francklin', 'Checchetelli', '683 Little Fleur Drive', 50, 1447.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (374, 'Virgil', 'Petrillo', '9 Bluestem Point', 70, 1925.18, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (375, 'Danila', 'Stirland', '6892 Welch Alley', 80, 364.88, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (376, 'Nikita', 'Tulloch', '2275 Texas Center', 98, 924.94, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (377, 'Melvin', 'McGlade', '750 Drewry Court', 58, 1657.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (378, 'Allin', 'Benezeit', '1 Ludington Road', 28, 1855.62, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (379, 'Miltie', 'Scarrisbrick', '12 Lakewood Junction', 81, 764.04, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (380, 'Casi', 'Moncey', '3903 Gale Plaza', 62, 1055.52, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (381, 'Kamillah', 'Snelgar', '21 Eggendart Park', 24, 1049.49, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (382, 'Darda', 'Cuniam', '3627 Loomis Trail', 57, 279.1, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (383, 'Filip', 'Miliffe', '100 Blaine Alley', 52, 1099.04, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (384, 'Den', 'Lisett', '281 Eliot Place', 29, 1735.39, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (385, 'Sander', 'Pauletto', '8313 Elmside Alley', 13, 242.17, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (386, 'Danie', 'Nock', '5 Manley Hill', 99, 25.66, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (387, 'Granville', 'Deackes', '30 Bartelt Road', 98, 684.54, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (388, 'Doretta', 'Mitcham', '5627 Kedzie Place', 83, 1255.26, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (389, 'Mellicent', 'Gebb', '599 Golden Leaf Point', 95, 791.16, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (390, 'Lynda', 'Lindsay', '0483 Meadow Ridge Terrace', 71, 1480.45, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (391, 'Emmalee', 'Bloschke', '44095 Debra Circle', 16, 1884.36, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (392, 'Mandie', 'Ilyin', '81512 Calypso Place', 36, 946.97, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (393, 'Wilie', 'Frankes', '29677 Eagle Crest Pass', 52, 1664.44, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (394, 'Julina', 'Mechell', '31 Shoshone Street', 26, 1761.19, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (395, 'Biron', 'Crosdill', '40463 Hudson Park', 44, 663.31, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (396, 'Lynn', 'Daouse', '13145 Granby Junction', 26, 1687.88, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (397, 'Gianni', 'Mulqueen', '43 Melby Circle', 29, 1118.4, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (398, 'Lyndell', 'Yurenev', '6229 Sommers Park', 9, 284.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (399, 'Carolyne', 'Loudiane', '425 Mallory Center', 48, 759.05, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (400, 'Homerus', 'Glanfield', '903 Aberg Plaza', 1, 409.69, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (401, 'Waldo', 'Coucha', '8 Utah Park', 92, 297.97, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (402, 'Rheta', 'Fernanando', '91 Shopko Point', 4, 264.27, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (403, 'Janaya', 'Guesford', '971 Nevada Road', 60, 1282.18, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (404, 'Marlon', 'Piele', '4 Knutson Parkway', 1, 131.87, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (405, 'Jasmin', 'O''Corhane', '510 Maryland Place', 1, 960.67, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (406, 'Fraze', 'Vegas', '50300 Village Parkway', 73, 321.02, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (407, 'Nicky', 'Flamank', '1794 Grasskamp Avenue', 21, 596.91, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (408, 'Vitoria', 'Carlo', '9 Main Court', 34, 1779.17, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (409, 'Bartlet', 'Grumble', '49 Ramsey Court', 2, 593.72, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (410, 'Arvin', 'Acom', '7 Kingsford Hill', 58, 1565.83, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (411, 'Gabbie', 'Jerzyk', '1494 Bobwhite Center', 37, 598.47, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (412, 'Jeanie', 'Halsted', '64 Elmside Place', 40, 218.68, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (413, 'Ricard', 'Snaddon', '88 Bunker Hill Drive', 26, 292.44, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (414, 'De witt', 'Palfery', '941 Jenifer Way', 72, 280.86, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (415, 'Nadine', 'Cosh', '0 Sunbrook Circle', 24, 580.69, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (416, 'Wynn', 'Dundridge', '5 Macpherson Place', 53, 51.22, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (417, 'Auroora', 'Gentzsch', '84310 Anniversary Junction', 66, 1817.4, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (418, 'Cherye', 'Couroy', '532 Fair Oaks Parkway', 82, 907.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (419, 'Barnaby', 'Greenset', '904 New Castle Drive', 14, 1612.99, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (420, 'Derwin', 'Keefe', '89 Fuller Street', 68, 11.38, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (421, 'Lib', 'Brantzen', '8557 Chinook Place', 56, 1864.19, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (422, 'Noni', 'Jiggins', '47743 Badeau Way', 49, 1492.94, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (423, 'Maude', 'Darton', '056 Hauk Alley', 75, 339.71, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (424, 'Vernon', 'Cocke', '628 Washington Trail', 36, 1286.62, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (425, 'Pen', 'Bilborough', '72 Linden Alley', 18, 1814.37, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (426, 'Venita', 'Callister', '28 6th Plaza', 92, 973.02, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (427, 'Hyacinthe', 'Corssen', '6409 Anderson Pass', 25, 862.99, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (428, 'Rafaela', 'Whipple', '50255 Columbus Avenue', 11, 103.37, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (429, 'Dodie', 'Todarini', '78 Waywood Lane', 56, 133.23, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (430, 'Rhetta', 'Garnul', '0501 Bunker Hill Lane', 87, 1384.47, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (431, 'Warde', 'Lumox', '75686 Evergreen Junction', 54, 1581.25, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (432, 'Bren', 'Mauchline', '901 Lakewood Center', 85, 1523.16, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (433, 'Bernie', 'Labram', '82 Northport Crossing', 23, 1376.33, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (434, 'Tess', 'McGloin', '5617 Shoshone Street', 4, 43.78, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (435, 'Leland', 'Tack', '25280 Darwin Junction', 62, 751.86, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (436, 'Rem', 'Hasnip', '31560 Armistice Point', 78, 1355.22, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (437, 'Ethan', 'Doble', '98 Buhler Park', 60, 254.82, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (438, 'Ciro', 'Coolbear', '896 Sheridan Place', 50, 1359.98, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (439, 'Velma', 'Jimson', '7 Gateway Street', 9, 1537.42, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (440, 'Farleigh', 'Broadis', '3 Carioca Terrace', 86, 903.66, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (441, 'Maxie', 'Phizacklea', '83 Service Point', 18, 1463.57, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (442, 'Jasmine', 'Longhorn', '7 Karstens Street', 86, 120.48, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (443, 'Rusty', 'Patriche', '79 Coolidge Court', 39, 1131.36, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (444, 'Rollie', 'Boddie', '76179 Holmberg Drive', 65, 933.55, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (445, 'Carlyle', 'Weatherhead', '8117 Westend Parkway', 43, 330.33, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (446, 'Nicoline', 'Penhall', '29 Shopko Avenue', 20, 1415.5, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (447, 'Beverie', 'Glavias', '6 Ryan Plaza', 45, 1242.66, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (448, 'Raviv', 'Keppie', '20476 Porter Park', 60, 1325.47, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (449, 'Nelson', 'Grimsdike', '1393 Longview Drive', 77, 1779.42, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (450, 'Gabe', 'Riseam', '1 Canary Center', 6, 1405.46, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (451, 'Justen', 'Jaulmes', '6 Almo Point', 70, 207.83, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (452, 'Grady', 'Pagan', '3605 Westridge Place', 45, 1171.5, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (453, 'Zola', 'Oldall', '856 Sunnyside Center', 73, 1204.91, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (454, 'Alissa', 'Gerold', '28 Eliot Point', 90, 964.58, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (455, 'Filbert', 'Paraman', '67556 Sutherland Junction', 3, 39.32, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (456, 'Moises', 'Kira', '97868 Blue Bill Park Avenue', 48, 1684.0, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (457, 'Perren', 'Kinde', '4891 Lotheville Crossing', 28, 767.64, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (458, 'Perry', 'Beglin', '6 Swallow Pass', 58, 338.31, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (459, 'Felisha', 'Grellis', '6557 Merry Drive', 21, 931.72, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (460, 'Shaughn', 'Scutter', '76598 Tomscot Parkway', 35, 730.18, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (461, 'Paulita', 'Hazel', '468 Ilene Road', 15, 1100.22, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (462, 'Davidson', 'Southerns', '4855 Sachs Alley', 49, 1057.78, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (463, 'Hayley', 'Bessell', '056 Bobwhite Street', 84, 1761.79, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (464, 'Domeniga', 'Santus', '5011 Fuller Street', 14, 1148.62, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (465, 'Teddie', 'Knights', '0 Old Shore Trail', 96, 1606.35, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (466, 'Phillipe', 'Kedie', '5 Melody Drive', 7, 1744.98, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (467, 'Felecia', 'Dovidaitis', '19 Miller Trail', 63, 927.16, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (468, 'Lilyan', 'Blackledge', '6 Burning Wood Avenue', 47, 746.34, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (469, 'Consuela', 'Innett', '0 Golf Crossing', 30, 709.98, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (470, 'Minor', 'Verecker', '97 Di Loreto Place', 47, 1236.28, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (471, 'Berri', 'Dooly', '6 Armistice Lane', 44, 1729.74, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (472, 'Gene', 'Pellington', '6841 Hoepker Terrace', 40, 1530.17, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (473, 'Philomena', 'Brotherhood', '6771 Muir Court', 37, 939.4, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (474, 'Tannie', 'Edgley', '8 Old Shore Alley', 36, 1325.27, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (475, 'Lowrance', 'Eliyahu', '436 Shoshone Junction', 62, 1675.47, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (476, 'Barnabas', 'Alecock', '7203 Esker Pass', 97, 1317.83, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (477, 'Josiah', 'Ruffler', '658 Hovde Trail', 26, 1517.79, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (478, 'Brande', 'Juszczyk', '44 Becker Park', 82, 1863.6, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (479, 'Whitney', 'Dudman', '5906 Melby Hill', 98, 636.35, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (480, 'Gael', 'Goacher', '5 La Follette Junction', 14, 1502.23, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (481, 'Chaddie', 'Lockner', '43150 Hermina Parkway', 78, 577.22, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (482, 'Marget', 'Byrd', '634 Springview Hill', 6, 337.21, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (483, 'Sander', 'Laugheran', '03 Duke Park', 83, 1001.44, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (484, 'Bartie', 'Manuaud', '2453 Brentwood Hill', 96, 1077.35, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (485, 'Eilis', 'Matthesius', '63900 Huxley Point', 27, 1369.06, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (486, 'Eveline', 'Shyram', '0331 Fordem Place', 60, 509.38, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (487, 'Marne', 'Romagnosi', '4391 International Alley', 80, 1087.53, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (488, 'Christel', 'Saterthwait', '49342 Dapin Street', 50, 1912.53, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (489, 'Heidi', 'Saunders', '799 Grim Way', 8, 1425.12, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (490, 'Burton', 'Babst', '63080 Cherokee Trail', 53, 150.34, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (491, 'Correy', 'Letrange', '37 Esch Terrace', 34, 1064.09, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (492, 'Basilio', 'Steart', '7 Magdeline Alley', 62, 544.55, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (493, 'Micki', 'Sirmond', '5 8th Lane', 56, 1478.38, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (494, 'Marlyn', 'Render', '63 Porter Way', 17, 1136.38, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (495, 'Nicky', 'Hoggin', '11 Corry Junction', 64, 78.14, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (496, 'Dodi', 'Claiton', '922 Mariners Cove Junction', 49, 1743.8, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (497, 'Idaline', 'Linskey', '092 Mayfield Junction', 92, 1123.45, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (498, 'Freddie', 'Revey', '61379 Di Loreto Crossing', 41, 1240.7, 'Da');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (499, 'Andreas', 'Kesterton', '476 Havey Hill', 41, 1344.68, 'Ne');
insert into Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard) values (500, 'Symon', 'Wallege', '62 Russell Court', 93, 917.87, 'Ne');
INSERT INTO Users (UserId, FirstName, LastName, Address, OrdersMade, MoneySpent, LoyaltyCard)
VALUES 
(501, 'Ivan', 'Markovic', 'Zagreb, Croatia', 5, 150.00, 'Ne'),
(502, 'Ana', 'Horvat', 'Split, Croatia', 20, 800.00, 'Da'),
(503, 'Maja', 'Mikic', 'Zadar, Croatia', 12, 350.00, 'Ne'),
(504, 'Luka', 'Maric', 'Zagreb, Croatia', 30, 1200.00, 'Da'),
(505, 'Petra', 'Marelic', 'Osijek, Croatia', 18, 600.00, 'Ne');

